"""Second strict frontier: parameterized recurrence, radix, and number-theory programs."""
from __future__ import annotations
import hashlib,json
from .metamachine_gen2 import *
from .strict_parametric_frontier import _assemble

def advanced_parametric_programs():
 p={}
 p["affine"]=(3,_assemble(((OP_GROW,2),(OP_LOAD_INPUT,2),(OP_STORE_CELL,"c"),(OP_LOAD_INPUT,0),(OP_STORE_CELL,"r"),"loop",(OP_LOAD_CELL,"c"),(OP_JUMP_IF_ZERO,"end"),(OP_LOAD_CELL,"r"),(OP_ADD_INPUT,1),(OP_STORE_CELL,"r"),(OP_LOAD_CELL,"c"),(OP_SUB_IMMEDIATE,1),(OP_STORE_CELL,"c"),(OP_JUMP,"loop"),"end",(OP_LOAD_CELL,"r"),(OP_EMIT,0),(OP_HALT,0)),("c","r")))
 p["arithmetic_sum"]=(3,_assemble(((OP_GROW,3),(OP_LOAD_INPUT,2),(OP_STORE_CELL,"c"),(OP_LOAD_INPUT,0),(OP_STORE_CELL,"term"),(OP_SET,0),(OP_STORE_CELL,"sum"),"loop",(OP_LOAD_CELL,"c"),(OP_JUMP_IF_ZERO,"end"),(OP_LOAD_CELL,"sum"),(OP_ADD_CELL,"term"),(OP_STORE_CELL,"sum"),(OP_LOAD_CELL,"term"),(OP_ADD_INPUT,1),(OP_STORE_CELL,"term"),(OP_LOAD_CELL,"c"),(OP_SUB_IMMEDIATE,1),(OP_STORE_CELL,"c"),(OP_JUMP,"loop"),"end",(OP_LOAD_CELL,"sum"),(OP_EMIT,0),(OP_HALT,0)),("c","term","sum")))
 p["rising"]=(2,_assemble(((OP_GROW,5),(OP_LOAD_INPUT,1),(OP_STORE_CELL,"outer"),(OP_LOAD_INPUT,0),(OP_STORE_CELL,"factor"),(OP_SET,1),(OP_STORE_CELL,"result"),"outer_loop",(OP_LOAD_CELL,"outer"),(OP_JUMP_IF_ZERO,"end"),(OP_LOAD_CELL,"result"),(OP_STORE_CELL,"inner"),(OP_SET,0),(OP_STORE_CELL,"temp"),"inner_loop",(OP_LOAD_CELL,"inner"),(OP_JUMP_IF_ZERO,"after_inner"),(OP_LOAD_CELL,"temp"),(OP_ADD_CELL,"factor"),(OP_STORE_CELL,"temp"),(OP_LOAD_CELL,"inner"),(OP_SUB_IMMEDIATE,1),(OP_STORE_CELL,"inner"),(OP_JUMP,"inner_loop"),"after_inner",(OP_LOAD_CELL,"temp"),(OP_STORE_CELL,"result"),(OP_LOAD_CELL,"factor"),(OP_ADD_IMMEDIATE,1),(OP_STORE_CELL,"factor"),(OP_LOAD_CELL,"outer"),(OP_SUB_IMMEDIATE,1),(OP_STORE_CELL,"outer"),(OP_JUMP,"outer_loop"),"end",(OP_LOAD_CELL,"result"),(OP_EMIT,0),(OP_HALT,0)),("outer","factor","result","inner","temp")))
 p["generalized_fibonacci"]=(3,_assemble(((OP_GROW,4),(OP_LOAD_INPUT,2),(OP_STORE_CELL,"c"),(OP_LOAD_INPUT,0),(OP_STORE_CELL,"a"),(OP_LOAD_INPUT,1),(OP_STORE_CELL,"b"),"loop",(OP_LOAD_CELL,"c"),(OP_JUMP_IF_ZERO,"end"),(OP_LOAD_CELL,"a"),(OP_ADD_CELL,"b"),(OP_STORE_CELL,"next"),(OP_LOAD_CELL,"b"),(OP_STORE_CELL,"a"),(OP_LOAD_CELL,"next"),(OP_STORE_CELL,"b"),(OP_LOAD_CELL,"c"),(OP_SUB_IMMEDIATE,1),(OP_STORE_CELL,"c"),(OP_JUMP,"loop"),"end",(OP_LOAD_CELL,"a"),(OP_EMIT,0),(OP_HALT,0)),("c","a","b","next")))
 radix=((OP_GROW,4),(OP_LOAD_INPUT,0),(OP_STORE_CELL,"value"),(OP_SET,"COUNT_SEED"),(OP_STORE_CELL,"count"),"outer",(OP_LOAD_CELL,"value"),(OP_JUMP_IF_ZERO,"end"),(OP_SET,0),(OP_STORE_CELL,"quotient"),(OP_LOAD_CELL,"value"),(OP_STORE_CELL,"remainder"),"divide",(OP_LOAD_CELL,"remainder"),(OP_SUB_INPUT,1),(OP_JUMP_IF_NEGATIVE,"after_div"),(OP_STORE_CELL,"remainder"),(OP_LOAD_CELL,"quotient"),(OP_ADD_IMMEDIATE,1),(OP_STORE_CELL,"quotient"),(OP_JUMP,"divide"),"after_div",(OP_LOAD_CELL,"quotient"),(OP_STORE_CELL,"value"),(OP_LOAD_CELL,"count"),(OP_ADD_IMMEDIATE,1),(OP_STORE_CELL,"count"),(OP_JUMP,"outer"),"end",(OP_LOAD_CELL,"count"),(OP_EMIT,0),(OP_HALT,0))
 def radix_program(seed):return _assemble(tuple((op,seed) if isinstance(x,tuple) and (op:=x[0])==OP_SET and x[1]=="COUNT_SEED" else x for x in radix),("value","count","quotient","remainder"))
 p["digit_length"]=(2,radix_program(0));p["floor_log"]=(2,radix_program(-1))
 p["lcm"]=(2,_assemble(((OP_LOAD_INPUT,0),(OP_JUMP_IF_ZERO,"zero"),(OP_LOAD_INPUT,1),(OP_JUMP_IF_ZERO,"zero"),(OP_GROW,2),(OP_LOAD_INPUT,0),(OP_STORE_CELL,"candidate"),"outer",(OP_LOAD_CELL,"candidate"),(OP_STORE_CELL,"remainder"),"reduce",(OP_LOAD_CELL,"remainder"),(OP_SUB_INPUT,1),(OP_JUMP_IF_NEGATIVE,"advance"),(OP_STORE_CELL,"remainder"),(OP_JUMP_IF_ZERO,"end"),(OP_JUMP,"reduce"),"advance",(OP_LOAD_CELL,"candidate"),(OP_ADD_INPUT,0),(OP_STORE_CELL,"candidate"),(OP_JUMP,"outer"),"end",(OP_LOAD_CELL,"candidate"),(OP_EMIT,0),(OP_HALT,0),"zero",(OP_SET,0),(OP_EMIT,0),(OP_HALT,0)),("candidate","remainder")))
 p["mod_power"]=(3,_assemble(((OP_GROW,4),(OP_LOAD_INPUT,2),(OP_SUB_IMMEDIATE,1),(OP_JUMP_IF_ZERO,"mod_one"),(OP_LOAD_INPUT,1),(OP_STORE_CELL,"outer"),(OP_SET,1),(OP_STORE_CELL,"result"),"outer_loop",(OP_LOAD_CELL,"outer"),(OP_JUMP_IF_ZERO,"end"),(OP_LOAD_INPUT,0),(OP_STORE_CELL,"inner"),(OP_SET,0),(OP_STORE_CELL,"temp"),"inner_loop",(OP_LOAD_CELL,"inner"),(OP_JUMP_IF_ZERO,"after_inner"),(OP_LOAD_CELL,"temp"),(OP_ADD_CELL,"result"),(OP_STORE_CELL,"temp"),"reduce",(OP_LOAD_CELL,"temp"),(OP_SUB_INPUT,2),(OP_JUMP_IF_NEGATIVE,"reduced"),(OP_STORE_CELL,"temp"),(OP_JUMP,"reduce"),"reduced",(OP_LOAD_CELL,"inner"),(OP_SUB_IMMEDIATE,1),(OP_STORE_CELL,"inner"),(OP_JUMP,"inner_loop"),"after_inner",(OP_LOAD_CELL,"temp"),(OP_STORE_CELL,"result"),(OP_LOAD_CELL,"outer"),(OP_SUB_IMMEDIATE,1),(OP_STORE_CELL,"outer"),(OP_JUMP,"outer_loop"),"end",(OP_LOAD_CELL,"result"),(OP_EMIT,0),(OP_HALT,0),"mod_one",(OP_SET,0),(OP_EMIT,0),(OP_HALT,0)),("outer","result","inner","temp")))
 p["geometric_sum"]=(2,_assemble(((OP_GROW,5),(OP_LOAD_INPUT,1),(OP_STORE_CELL,"outer"),(OP_SET,1),(OP_STORE_CELL,"power"),(OP_SET,1),(OP_STORE_CELL,"sum"),"outer_loop",(OP_LOAD_CELL,"outer"),(OP_JUMP_IF_ZERO,"end"),(OP_LOAD_CELL,"power"),(OP_STORE_CELL,"inner"),(OP_SET,0),(OP_STORE_CELL,"temp"),"inner_loop",(OP_LOAD_CELL,"inner"),(OP_JUMP_IF_ZERO,"after_inner"),(OP_LOAD_CELL,"temp"),(OP_ADD_INPUT,0),(OP_STORE_CELL,"temp"),(OP_LOAD_CELL,"inner"),(OP_SUB_IMMEDIATE,1),(OP_STORE_CELL,"inner"),(OP_JUMP,"inner_loop"),"after_inner",(OP_LOAD_CELL,"temp"),(OP_STORE_CELL,"power"),(OP_LOAD_CELL,"sum"),(OP_ADD_CELL,"power"),(OP_STORE_CELL,"sum"),(OP_LOAD_CELL,"outer"),(OP_SUB_IMMEDIATE,1),(OP_STORE_CELL,"outer"),(OP_JUMP,"outer_loop"),"end",(OP_LOAD_CELL,"sum"),(OP_EMIT,0),(OP_HALT,0)),("outer","power","sum","inner","temp")))
 p["second_difference"]=(4,_assemble(((OP_GROW,3),(OP_LOAD_INPUT,3),(OP_STORE_CELL,"c"),(OP_LOAD_INPUT,0),(OP_STORE_CELL,"value"),(OP_LOAD_INPUT,1),(OP_STORE_CELL,"delta"),"loop",(OP_LOAD_CELL,"c"),(OP_JUMP_IF_ZERO,"end"),(OP_LOAD_CELL,"value"),(OP_ADD_CELL,"delta"),(OP_STORE_CELL,"value"),(OP_LOAD_CELL,"delta"),(OP_ADD_INPUT,2),(OP_STORE_CELL,"delta"),(OP_LOAD_CELL,"c"),(OP_SUB_IMMEDIATE,1),(OP_STORE_CELL,"c"),(OP_JUMP,"loop"),"end",(OP_LOAD_CELL,"value"),(OP_EMIT,0),(OP_HALT,0)),("c","value","delta")))
 return p

class AdvancedParametricFrontierSearch:
 def __init__(self,top_k=100,executor=None):self.top_k=top_k;self.executor=executor or ReflectiveExecutor(maximum_steps=200000);self.catalog=advanced_parametric_programs()
 def search(self,observation):
  valid=tuple((r,o) for r,o,v in zip(observation.input_rows,observation.output_values,observation.validity_mask) if v);width=len(valid[0][0]);programs=[p for arity,p in self.catalog.values() if arity==width];candidates=[];rejected=0
  for program in programs:
   try:outputs=tuple(self.executor.execute(program,row).output_value for row,_ in valid)
   except InvalidReflectiveProgram:rejected+=1;continue
   errors=tuple(a-float(y) for a,(_,y) in zip(outputs,valid));key=json.dumps(program.to_dict(),sort_keys=True,separators=(",",":"));candidates.append(ReflectiveCandidate("AP-"+hashlib.sha256(key.encode()).hexdigest()[:16],program,sum(e*e for e in errors)/len(errors),max(abs(e) for e in errors),outputs,outputs))
  candidates.sort(key=lambda c:(c.fit_error,c.program.instruction_count,c.maximum_absolute_error,c.candidate_id));return ReflectiveSearchReport(len(programs),len(candidates),rejected,len({c.outputs for c in candidates}),tuple(candidates[:self.top_k]))
