import data from "../../data/official_dynamic_science_v41_latest.json";

const r=data,a=r.acceptance,d=a.discovery,h=a.history_dependence_audit,f=a.future_trajectory_audit,x=a.cross_cell_replication_audit,p=a.dataset.provenance_audit,z=a.semantic_compression_audit,g=a.discovery_gates,c=a.claim_state;
const stateless=d.candidates.find(item=>item.kind==="stateless")!;
const persistence=d.candidates.find(item=>item.kind==="persistence")!;
const gateRows=[
  ["NASA 官方来源",g.official_nasa_provenance],["真实物理实验档案",g.real_physical_experiment_archive],
  ["随机控制序列",g.randomized_control_profiles],["独立密封进程",g.separate_sealed_archive_process],
  ["匿名通道",g.domain_blind_channels],["未来分区承诺锁",g.future_partition_locked_until_commitment],
  ["历史依赖反例",g.history_dependence_counterexample],["STATE_FOLD 已创建",g.state_fold_operator_created],
  ["击败无记忆程序",g.stateful_program_beats_stateless],["未来轨迹预测",g.prospective_future_trajectory_prediction],
  ["跨电池复现",g.cross_cell_replication],["重复步骤压缩",g.repeated_steps_compressed],
];

export default function Page(){return <main>
<header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">OFFICIAL DYNAMIC SCIENCE V41</p><p className="brand-name">AKGM-N0 / NASA 匿名动态状态发现</p></div></div><div className="run-meta"><a className="nav-link" href="/science-v41-challenge">盲测挑战</a><a className="nav-link" href="/science-v40">物理装置 V40</a><a className="nav-link" href="/science-v39">在线实验 V39</a><a className="nav-link" href="/">总览</a></div></header>
<section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">V41 验收 15/15</span><span className="scope-label">ANONYMIZE → COUNTEREXAMPLE → STATE → FOLD → PREDICT → REPLICATE</span></div><h1>系统从 NASA 官方轨迹中发现：当前输入不足以决定未来</h1><p className="lede">100 条真实电池随机负载轨迹被转换成 Q0–Q3 匿名通道。系统先找到同条件不同响应的反例，再把“读取前态—执行更新—写回状态”的重复程序压缩成 STATE_FOLD。</p><div className="run-id"><span>LATEST</span><code>{r.run_id}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>{a.passed?"PASS":"BLOCK"}</strong><span>动态状态发现</span></div><p>历史官方数据；不是新现场测量</p></div></section>
<section className="metric-grid"><article className="metric-card accent-cyan"><p>官方轨迹</p><strong>{p.trace_count}</strong><span>40/20/20/20 四分区</span></article><article className="metric-card accent-violet"><p>历史反例差值</p><strong>{h.response_difference.toFixed(3)}</strong><span>相似输入，响应显著不同</span></article><article className="metric-card accent-amber"><p>未来轨迹 RMSE</p><strong>{f.rmse.toFixed(3)}</strong><span>{f.trace_count} 条时间后移轨迹</span></article><article className="metric-card accent-cyan"><p>跨电池 RMSE</p><strong>{x.rmse.toFixed(3)}</strong><span>{x.trace_count} 条 RW4 轨迹</span></article></section>
<section className="content-grid operation-grid"><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">MEMORY NECESSITY</p><h2>状态程序击败无记忆程序</h2></div><span className="evidence-chip">误差比 {(d.stateful_to_stateless_rmse_ratio*100).toFixed(1)}%</span></div><div className="bar-chart"><div className="bar-row"><div className="bar-label"><span>STATE_FOLD</span><strong>{d.selected.validation_rmse.toFixed(5)}</strong></div><div className="bar-track"><div className="bar library" style={{width:`${100*d.selected.validation_rmse/stateless.validation_rmse}%`}} /></div></div><div className="bar-row"><div className="bar-label"><span>STATELESS</span><strong>{stateless.validation_rmse.toFixed(5)}</strong></div><div className="bar-track"><div className="bar baseline" style={{width:"100%"}} /></div></div><div className="bar-row"><div className="bar-label"><span>PERSISTENCE</span><strong>{persistence.validation_rmse.toFixed(5)}</strong></div><div className="bar-track"><div className="bar baseline" style={{width:`${Math.min(100,100*persistence.validation_rmse/stateless.validation_rmse)}%`}} /></div></div></div></article><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">COUNTEREXAMPLE</p><h2>匿名条件近似相同，Q1 不相同</h2></div></div><div className="posthoc-note"><strong>ΔQ1 = {h.response_difference.toFixed(3)}</strong><small>案例 A：Q0={h.case_a.q0.toFixed(2)}, Q1={h.case_a.q1.toFixed(3)}, Q3={h.case_a.q3.toFixed(1)}<br/>案例 B：Q0={h.case_b.q0.toFixed(2)}, Q1={h.case_b.q1.toFixed(3)}, Q3={h.case_b.q3.toFixed(1)}</small></div><p className="concept-footnote">这迫使系统引入历史状态；它不能再把响应写成当前匿名输入的静态函数。</p></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">CREATED OPERATOR</p><h2>STATE_FOLD：把重复状态更新压缩成一个运算</h2></div></div><div className="boundary-box"><p>{d.selected.program_id}</p><code>{d.selected.opaque_program}</code><span>每条轨迹从 {z.uncompressed_nodes_per_trace} 个展开节点压缩到 {z.compressed_call_nodes_per_trace} 个调用节点，压缩率 {z.compression_ratio.toFixed(1)}×。</span></div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">OFFICIAL DATA RECEIPT</p><h2>NASA Ames 原档案与派生快照均已封存</h2></div></div><div className="operator-discovery-grid"><article className="metric-card"><p>PROVIDER</p><strong className="operator-name">NASA Ames PCoE</strong><span>公开物理试验档案</span></article><article className="metric-card"><p>ARCHIVE</p><strong className="operator-name">{(p.archive_bytes/1e6).toFixed(1)} MB</strong><span>SHA {p.archive_sha256.slice(0,16)}…</span></article><article className="metric-card"><p>SNAPSHOT</p><strong className="operator-name">100 TRACES</strong><span>SHA {p.snapshot_sha256.slice(0,16)}…</span></article><article className="metric-card"><p>SOURCE</p><strong className="operator-name"><a className="nav-link" href={p.landing_page}>NASA OPEN DATA</a></strong><span>Randomized Battery Usage 2</span></article></div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">VERIFICATION GATES</p><h2>动态发现证据链</h2></div></div><div className="operator-discovery-grid">{gateRows.map(([name,passed])=><article className="metric-card" key={String(name)}><p>{name}</p><strong className="operator-name">{passed?"PASS":"FAIL"}</strong><span>{passed?"证据已登记":"验收失败"}</span></article>)}<article className="metric-card"><p>本项目现场新测量</p><strong className="operator-name">BLOCKED</strong><span>NASA 历史档案</span></article><article className="metric-card"><p>人类未知自然定律</p><strong className="operator-name">BLOCKED</strong><span>禁止升级声明</span></article></div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">CLAIM BOUNDARY</p><h2>发现了必要的状态语义，没有宣称发明电化学</h2></div></div><div className="boundary-box"><p>当前标签</p><code>{c.current_label}</code><span>事后翻译：Q0=电流，Q1=端电压，Q2=温度，Q3=脉冲经过时间。</span></div><ul>{a.limitations.map(item=><li key={item}>{item}</li>)}</ul></section>
</main>}
