import reportData from "../../data/continuous_dynamics_v28_latest.json";
const report = reportData;
const a = report.acceptance;
const d = a.discovery;
const g = a.mechanics_capability_graph;
const passed = a.proof_obligations.filter(item => item.passed).length;

export default function MechanicsV28Page() {
  return <main>
    <header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">CONTINUOUS DYNAMICS V28</p><p className="brand-name">AKGM-N0 / 时间算子与极限证书</p></div></div><div className="run-meta"><a className="nav-link" href="/mechanics-v29">约束力学 V29</a><a className="nav-link" href="/mechanics-v27">刚体力学</a><a className="nav-link" href="/mechanics-v26">旋转力学</a><a className="nav-link" href="/mistakes">错题库</a><a className="nav-link" href="/">总览</a></div></header>
    <section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">V28 验收 {passed}/12</span><span className="scope-label">SAMPLE → SEARCH → REFINE → LIMIT → PROMOTE</span></div><h1>系统从离散状态进入有极限证书的连续时间动力学</h1><p className="lede">学习器只看到三个匿名时间样本、一个时间间隔和两个匿名目标。每个目标在750个路由中唯一选出；随后通过不同分辨率实验发现二阶收敛，而不是直接获得导数公式。</p><div className="run-id"><span>LATEST</span><code>{report.run_id}</code><code>{a.classification}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>{g.verified_domains}/{g.total_domains}</strong><span>力学领域</span></div><p>下一项：{g.next_selected_gap}</p></div></section>
    <section className="metric-grid meta-score-grid"><article className="metric-card accent-cyan"><p>每目标候选</p><strong>{d.candidates_per_target}</strong><span>唯一各选一个</span></article><article className="metric-card accent-violet"><p>收敛阶</p><strong>{d.selected_refinement_order}</strong><span>步长减半，误差四分之一</span></article><article className="metric-card accent-amber"><p>训练轨迹</p><strong>{d.training_cases}</strong><span>匿名二次轨迹</span></article><article className="metric-card accent-cyan"><p>完成进度</p><strong>{g.verified_domains}/{g.total_domains}</strong><span>完整标签仍被禁止</span></article></section>
    <section className="content-grid operation-grid"><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">FIRST TIME OPERATOR</p><h2>D_T</h2></div><span className="status-chip good">UNIQUE</span></div><div className="posthoc-note"><span>匿名程序</span><strong><code>{d.selected_target_0.opaque_program}</code></strong></div><div className="posthoc-note"><span>证明后翻译</span><strong>[x(t+h)−x(t−h)]/(2h)</strong><small>中心一阶时间算子。</small></div></article><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">SECOND TIME OPERATOR</p><h2>D_T²</h2></div><span className="status-chip good">UNIQUE</span></div><div className="posthoc-note"><span>匿名程序</span><strong><code>{d.selected_target_1.opaque_program}</code></strong></div><div className="posthoc-note"><span>证明后翻译</span><strong>[x(t+h)−2x(t)+x(t−h)]/h²</strong><small>中心二阶时间算子。</small></div></article></section>
    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">LIMIT CERTIFICATE</p><h2>不是把差分直接叫作导数</h2></div></div><div className="operator-discovery-grid"><article className="metric-card"><p>QUADRATIC</p><strong className="operator-name">完全精确</strong><span>任意正有理步长</span></article><article className="metric-card"><p>CUBIC</p><strong className="operator-name">误差 = C·h²</strong><span>不同分辨率验证</span></article><article className="metric-card"><p>REFINEMENT</p><strong className="operator-name">h/2 → error/4</strong><span>二阶极限证书</span></article><article className="metric-card"><p>MECHANICS</p><strong className="operator-name">F = mD_T²x</strong><span>V24 关系迁移</span></article></div></section>
    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">COMPLETENESS GATE</p><h2>8/15，继续运行</h2></div></div><div className="operator-discovery-grid">{g.domains.map(item => <article className="metric-card" key={item.capability_id}><p><code>{item.capability_id}</code></p><strong className="operator-name">{item.capability}</strong><span>{item.status === "verified" ? `已验证 · ${item.evidence_version}` : "尚未发现"}</span></article>)}</div><div className="boundary-box"><p>下一研究缺口</p><code>{g.next_selected_gap}</code><span>{g.selection_reason}</span></div></section>
    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">HONEST BOUNDARY</p><h2>当前连续性范围</h2></div></div><ul>{a.limitations.map(item => <li key={item}>{item}</li>)}</ul><div className="boundary-box"><p>准确成果</p><code>{report.claim.achieved}</code><span>未声称：{report.claim.not_claimed}</span></div></section>
  </main>;
}
