import data from "../../data/empirical_science_v37_latest.json";
const r=data,a=r.acceptance,d=a.discovery,m=a.dataset.metadata,h=a.holdout_audit,c=a.claim_state,g=a.discovery_gates;
const gateRows=[
  ["真实公开档案",g.real_public_archive_snapshot],["来源与查询可追溯",g.source_and_query_provenance],
  ["独立数据进程",g.separate_data_process],["匿名字段",g.anonymous_columns],
  ["承诺早于保留集揭晓",g.holdout_commit_before_reveal],["测量误差处理",g.measurement_uncertainty_handled],
  ["稳健模型胜出",g.robust_model_selection],["子样本稳定",g.bootstrap_stability],
  ["密封预测",g.holdout_prediction],["置乱零模型拒绝",g.null_model_rejection],
  ["已知规律匹配",g.known_law_catalog_match],["变量全部独立测量",g.independent_measurement_of_all_variables],
  ["人类新颖性",g.human_novelty],["外部实验室复现",g.external_laboratory_replication],
];
export default function Page(){return <main><header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">EMPIRICAL SCIENCE V37</p><p className="brand-name">AKGM-N0 / 真实档案、误差与密封预测</p></div></div><div className="run-meta"><a className="nav-link" href="/science-v38">因果干预 V38</a><a className="nav-link" href="/science-v36">发现门控 V36</a><a className="nav-link" href="/mechanics-v35">力学 15/15</a><a className="nav-link" href="/">总览</a></div></header>
<section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">V37 验收 14/14</span><span className="scope-label">NASA ARCHIVE → BLIND PROCESS → ROBUST FIT → COMMIT → HOLDOUT</span></div><h1>系统第一次在真实公开观测上完成匿名规律重发现</h1><p className="lede">53 行 NASA 系外行星档案被固定并散列。学习器只看到匿名量，在 81 个幂律模型中选择指数；保留集输出由独立进程锁定，只有预测承诺完成后才能揭晓。</p><div className="run-id"><span>LATEST</span><code>{r.run_id}</code><code>{a.classification}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>{c.real_data_pipeline_verified?"PASS":"BLOCK"}</strong><span>真实数据管线</span></div><p>结论：已知规律重发现</p></div></section>
<section className="metric-grid meta-score-grid"><article className="metric-card accent-cyan"><p>真实记录</p><strong>{m.rows}</strong><span>训练 {m.train_rows} / 保留 {m.holdout_rows}</span></article><article className="metric-card accent-violet"><p>候选模型</p><strong>{d.candidate_count}</strong><span>半整数指数网格</span></article><article className="metric-card accent-amber"><p>子样本稳定性</p><strong>{Math.round(d.bootstrap_selection_rate*100)}%</strong><span>{d.bootstrap_runs} 次重选</span></article><article className="metric-card accent-cyan"><p>保留集 MAPE</p><strong>{(h.median_absolute_percentage_error*100).toFixed(2)}%</strong><span>区间覆盖 {(h.coverage*100).toFixed(0)}%</span></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">ANONYMOUS EMPIRICAL PROGRAM</p><h2>机器选出的真实数据关系</h2></div></div><div className="operator-discovery-grid"><article className="metric-card"><p>OPAQUE PROGRAM</p><strong className="operator-name" style={{minWidth:0}}><code style={{fontSize:"0.78rem",overflowWrap:"anywhere",whiteSpace:"normal"}}>{d.selected_program.opaque_program}</code></strong><span>搜索阶段没有物理名称</span></article><article className="metric-card"><p>POSTHOC</p><strong className="operator-name">P≈{d.selected_program.fitted_scale.toFixed(2)}a³ᐟ²M⁻¹ᐟ²</strong><span>天、AU、太阳质量</span></article><article className="metric-card"><p>RUNNER-UP GAP</p><strong className="operator-name">{d.score_margin.toFixed(3)}</strong><span>稳健标准化误差差距</span></article></div></section>
<section className="content-grid operation-grid"><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">SEALED HOLDOUT</p><h2>预测先于揭晓</h2></div></div><div className="posthoc-note"><strong>{a.preregistration.prediction_count} 个未来预测</strong><small>摘要 {a.preregistration.commitment.slice(0,20)}…；代理进程在承诺前拒绝输出。</small></div></article><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">NULL AUDIT</p><h2>不是任意配对都成立</h2></div></div><div className="posthoc-note"><strong>{a.null_audit.null_count} 组置乱全部更差</strong><small>真实关系得分 {a.null_audit.selected_score.toFixed(3)}；置乱最低 {Math.min(...a.null_audit.null_scores).toFixed(3)}。</small></div></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">EMPIRICAL GATES</p><h2>真实数据通过，不等于新科学通过</h2></div></div><div className="operator-discovery-grid">{gateRows.map(([name,passed])=><article className="metric-card" key={String(name)}><p>{name}</p><strong className="operator-name">{passed?"PASS":"BLOCKED"}</strong><span>{passed?"证据已登记":"禁止升级声明"}</span></article>)}</div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">CLAIM BOUNDARY</p><h2>真实数据上的已知规律重发现</h2></div></div><div className="boundary-box"><p>当前标签</p><code>{c.current_label}</code><span>半长轴可能由同一物理关系派生，因此不能作为完全独立验证。</span></div><ul>{a.limitations.map(i=><li key={i}>{i}</li>)}</ul></section></main>}
