import data from "../../data/live_randomized_science_v39_latest.json";

const r=data,a=r.acceptance,c=a.model_competition,h=a.prospective_holdout_audit,n=a.timing_noise_audit,x=a.new_process_replication_audit,p=a.adaptive_experiment_audit,g=a.discovery_gates,s=a.claim_state;
const passGates=[
  ["现场新测量",g.live_new_measurements],["独立装置进程",g.independent_apparatus_process],
  ["自适应选实验",g.adaptive_experiment_selection],["批次顺序随机化",g.randomized_batch_order],
  ["先承诺后测量",g.commit_before_measurement],["未见条件预测",g.prospective_holdout_prediction],
  ["计时噪声量化",g.timing_noise_quantified],["尺度律竞争",g.scale_law_competition],
  ["新进程复现",g.new_process_replication],["已知装置阶数匹配",g.known_kernel_scaling_match],
];
const blockedGates=[["自然物理系统",g.natural_physical_system],["外部实验室",g.external_laboratory],["人类未知发现",g.human_novelty]];

export default function Page(){return <main>
<header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">LIVE RANDOMIZED SCIENCE V39</p><p className="brand-name">AKGM-N0 / 在线实验规划与前瞻验证</p></div></div><div className="run-meta"><a className="nav-link" href="/science-v40">物理装置 V40</a><a className="nav-link" href="/science-v38">受控实验 V38</a><a className="nav-link" href="/science-v37">真实档案 V37</a><a className="nav-link" href="/">总览</a></div></header>
<section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">V39 验收 14/14</span><span className="scope-label">PLAN → RANDOMIZE → COMMIT → MEASURE → UPDATE → REPLICATE</span></div><h1>系统第一次闭合了现场、自适应、可复现的实验循环</h1><p className="lede">装置数据不是预先写入的表格。研究器先让九种尺度律竞争，再按候选分歧选择下一个条件；批次顺序与预测哈希先封存，独立进程随后才产生计时结果。</p><div className="run-id"><span>LATEST</span><code>{r.run_id}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>{a.passed?"PASS":"BLOCK"}</strong><span>在线实验闭环</span></div><p>自然科学新发现：仍阻断</p></div></section>
<section className="metric-grid"><article className="metric-card accent-cyan"><p>现场测量</p><strong>{a.measurements.length}</strong><span>由运行中的装置生成</span></article><article className="metric-card accent-violet"><p>自适应轮次</p><strong>{p.round_count}</strong><span>{p.unique_measured_levels} 个训练条件</span></article><article className="metric-card accent-amber"><p>发现指数</p><strong>{(c.selected.exponent_quarters/4).toFixed(2)}</strong><span>九种候选尺度律竞争</span></article><article className="metric-card accent-cyan"><p>未见条件误差</p><strong>{(h.absolute_percentage_error*100).toFixed(2)}%</strong><span>承诺后才测量</span></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">DISCOVERED PROGRAM</p><h2>获胜的匿名尺度语义</h2></div></div><div className="operator-discovery-grid"><article className="metric-card"><p>OPAQUE PROGRAM</p><strong className="operator-name"><code style={{fontSize:"0.72rem",overflowWrap:"anywhere",whiteSpace:"normal"}}>{c.selected.opaque_program}</code></strong><span>拟合比例 {c.selected.fitted_scale.toFixed(3)}</span></article><article className="metric-card"><p>RUNNER-UP</p><strong className="operator-name">Q0^{c.runner_up.exponent_quarters}/4</strong><span>鲁棒分数 {c.runner_up.robust_score.toFixed(3)}</span></article><article className="metric-card"><p>REPLICATION</p><strong className="operator-name">{(x.median_absolute_percentage_error*100).toFixed(2)}%</strong><span>新进程中位误差</span></article><article className="metric-card"><p>NOISE</p><strong className="operator-name">{(n.median_mad_fraction*100).toFixed(2)}%</strong><span>样本中位 MAD 比例</span></article></div></section>
<section className="content-grid operation-grid"><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">ADAPTIVE TRAJECTORY</p><h2>模型分歧决定下一次测量</h2></div></div><div className="receipt-list">{p.plans.map(plan=><div key={plan.round_index}><dt>ROUND {plan.round_index} · [{plan.selected_anonymous_levels.join(", ")}]</dt><dd>分歧 {plan.maximum_log_prediction_spread.toFixed(3)}</dd></div>)}</div></article><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">PROSPECTIVE HOLDOUT</p><h2>352 从未用于拟合</h2></div></div><div className="posthoc-note"><strong>预测 {h.predicted_response.toFixed(0)} / 实测 {h.observed_response.toFixed(0)}</strong><small>预测承诺事件 {h.prediction_commit_event_index} 早于测量事件 {h.measurement_event_index}；哈希 {h.prediction_commitment.slice(0,20)}…</small></div></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">VERIFICATION GATES</p><h2>协议能力通过，声明边界保持关闭</h2></div></div><div className="operator-discovery-grid">{passGates.map(([name,passed])=><article className="metric-card" key={String(name)}><p>{name}</p><strong className="operator-name">{passed?"PASS":"FAIL"}</strong><span>{passed?"证据已登记":"验收未通过"}</span></article>)}{blockedGates.map(([name,passed])=><article className="metric-card" key={String(name)}><p>{name}</p><strong className="operator-name">{passed?"OPEN":"BLOCKED"}</strong><span>禁止升级声明</span></article>)}</div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">CLAIM BOUNDARY</p><h2>这是实验方法突破，不是未知自然定律</h2></div></div><div className="boundary-box"><p>当前标签</p><code>{s.current_label}</code><span>真实时间测量 + 随机化 + 自适应选择 + 前瞻预测 + 新进程复现。</span></div><ul>{a.limitations.map(item=><li key={item}>{item}</li>)}</ul></section>
</main>}
