import reportData from "../../data/autonomous_physics_worlds_v23_latest.json";

const report = reportData;
const acceptance = report.acceptance;
const construction = acceptance.construction;
const worlds = construction.worlds.slice(0, 12);
const passed = acceptance.proof_obligations.filter(item => item.passed).length;
const graphName: Record<string, string> = { G0: "链式", G1: "环式", G2: "星式" };

export default function PhysicsWorldsV23Page() {
  return <main>
    <header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">AUTONOMOUS PHYSICS WORLDS V23</p><p className="brand-name">AKGM-N0 / 自主构造可执行宇宙</p></div></div><div className="run-meta"><a className="nav-link" href="/physics-v24">惯性响应 V24</a><a className="nav-link" href="/physics-v22">物理发现</a><a className="nav-link" href="/foundation-v21">有向有理数</a><a className="nav-link" href="/mistakes">错题库</a><a className="nav-link" href="/">总览</a></div></header>

    <section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">V23 验收 {passed}/12</span><span className="scope-label">GENERATE → EXECUTE → SCORE → PROVE → REPLAY</span></div><h1>系统现在能自己生成、运行和筛选多个物理世界</h1><p className="lede">世界工厂不接收逐个世界定义。它自主选择实体数量、交互图、初态、时间间隔和内部传递日程，再安装 V22 的状态转移程序执行多步模拟。只有确定、非平凡、量纲一致、成本有限且每一步保持封闭总量的世界才能进入成功房间。</p><div className="run-id"><span>LATEST</span><code>{report.run_id}</code><code>{acceptance.classification}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>{construction.worlds_accepted}/{construction.worlds_generated}</strong><span>世界通过</span></div><p>{acceptance.sealed_worlds.accepted_count}/6 密封世界迁移</p></div></section>

    <section className="metric-grid meta-score-grid">
      <article className="metric-card accent-cyan"><p>自主世界</p><strong>{construction.worlds_generated}</strong><span>没有逐世界人工定义</span></article>
      <article className="metric-card accent-violet"><p>图结构家族</p><strong>{construction.graph_family_count}</strong><span>链 · 环 · 星</span></article>
      <article className="metric-card accent-amber"><p>实体规模</p><strong>{construction.entity_count_range.join("–")}</strong><span>每个世界</span></article>
      <article className="metric-card accent-cyan"><p>实体推进</p><strong>{construction.total_simulated_steps}</strong><span>已执行状态转移</span></article>
      <article className="metric-card accent-slate"><p>内部交互</p><strong>{construction.total_interactions}</strong><span>平衡传递事件</span></article>
    </section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">WORLD CONSTRUCTION LOOP</p><h2>一个世界如何诞生</h2></div><span className="status-chip good">NO PER-WORLD HUMAN DESIGN</span></div><div className="operator-discovery-grid"><article className="metric-card"><p>01 / TOPOLOGY</p><strong className="operator-name">生成有限实体图</strong><span>G0、G1、G2 三种匿名家族</span></article><article className="metric-card"><p>02 / INITIALIZE</p><strong className="operator-name">生成三计数器初态</strong><span>允许正反方向与不同分母</span></article><article className="metric-card"><p>03 / INTERACT</p><strong className="operator-name">边两端施加相反传递</strong><span>每条边内部总变化为零</span></article><article className="metric-card"><p>04 / ADVANCE</p><strong className="operator-name">调用 V22 转移程序</strong><span>每个实体按世界时间步推进</span></article><article className="metric-card"><p>05 / NORMALIZE</p><strong className="operator-name">相消与欧几里得约分</strong><span>控制连续模拟状态膨胀</span></article><article className="metric-card"><p>06 / GATE</p><strong className="operator-name">七项世界质量门</strong><span>失败世界不得进入成功房间</span></article></div></section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">WORLD CATALOG</p><h2>前十二个自主世界</h2></div><span className="status-chip good">ALL ACCEPTED</span></div><div className="operator-discovery-grid">{worlds.map(world => <article className="metric-card" key={world.definition.world_id}><p><code>{world.definition.world_id}</code></p><strong className="operator-name">{graphName[world.definition.graph_family]} · {world.definition.initial_entities.length} entities</strong><span>{world.definition.edges.length} edges · {world.definition.step_count} steps · seed {world.definition.seed}</span><small>{world.execution.transition_count} transitions · {world.execution.interaction_count} interactions · digest {world.execution.deterministic_digest.slice(0, 12)}</small></article>)}</div></section>

    <section className="content-grid operation-grid"><article className="surface comparison-card"><div className="section-heading"><div><p className="eyebrow">QUALITY GATES</p><h2>不是所有随机配置都叫物理世界</h2></div><span className="status-chip good">24/24</span></div><div className="evidence-list">{Object.entries(construction.worlds[0].quality).filter(([key]) => key !== "accepted").map(([key, value]) => <div className="evidence-row" key={key}><div><strong>{key}</strong><span>每个世界独立检查</span></div><b>{value ? "PASS" : "FAIL"}</b></div>)}</div></article><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">UNIVERSAL WORLD PROOF</p><h2>为何所有图都守恒</h2></div></div><div className="receipt-list"><div><dt>finite graphs</dt><dd>proved</dd></div><div><dt>edge transfer</dt><dd>j / TURN(j)</dd></div><div><dt>edge net change</dt><dd>ZERO</dd></div><div><dt>whole graph total</dt><dd>conserved</dd></div></div><div className="posthoc-note"><span>证明后物理解释</span><strong>内部冲量成对作用，封闭世界的总动量式量保持</strong><small>当前实体隐含单位惯性，尚未构造质量依赖。</small></div></article></section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">SEALED WORLDS</p><h2>不同种子也能构造成功</h2></div></div><div className="operator-discovery-grid"><article className="metric-card"><p>SEED COMMITMENT</p><strong className="operator-name">{acceptance.sealed_worlds.seed_commitment}</strong><span>不属于主世界种子区间</span></article><article className="metric-card"><p>GENERATED</p><strong className="operator-name">{acceptance.sealed_worlds.world_count}</strong><span>8 步世界</span></article><article className="metric-card"><p>ACCEPTED</p><strong className="operator-name">{acceptance.sealed_worlds.accepted_count}</strong><span>全部质量门通过</span></article><article className="metric-card"><p>PROOF</p><strong className="operator-name">{acceptance.sealed_worlds.proof.passed ? "通过" : "失败"}</strong><span>独立轨迹重放</span></article></div></section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">MUTATION AUDIT</p><h2>破坏世界规则会发生什么</h2></div></div><div className="operator-discovery-grid">{acceptance.mutation_audits.map(item => <article className="metric-card" key={item.mutation}><p><code>{item.mutation}</code></p><strong className="operator-name">{item.rejected ? "已拒绝" : "未拒绝"}</strong><span>真实重放反例</span><small>{item.counterexample.world_id}</small></article>)}</div></section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">STRICT OBLIGATIONS</p><h2>十二项世界构造验收</h2></div></div><div className="operator-discovery-grid">{acceptance.proof_obligations.map(item => <article className="metric-card" key={item.obligation_id}><p><code>{item.obligation_id}</code></p><strong className="operator-name">{item.passed ? "通过" : "失败"}</strong><span>独立证据</span></article>)}</div></section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">HONEST BOUNDARY</p><h2>这是可执行的离散宇宙工厂，还不是现实宇宙模拟器</h2></div></div><ul>{acceptance.limitations.map(item => <li key={item}>{item}</li>)}</ul><div className="boundary-box"><p>准确成果</p><code>{report.claim.achieved}</code><span>未声称：{report.claim.not_claimed}</span></div><p className="digest-line">内容摘要 <code>{report.content_digest}</code></p></section>
  </main>;
}
