import reportData from "../../data/anonymous_physics_discovery_v22_latest.json";

const report = reportData;
const acceptance = report.acceptance;
const discovery = acceptance.discovery;
const proofs = acceptance.proofs;
const passed = acceptance.proof_obligations.filter(item => item.passed).length;

export default function PhysicsV22Page() {
  return <main>
    <header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">ANONYMOUS PHYSICS DISCOVERY V22</p><p className="brand-name">AKGM-N0 / 第一层自主物理</p></div></div><div className="run-meta"><a className="nav-link" href="/physics-worlds-v23">物理世界</a><a className="nav-link" href="/foundation-v21">有向有理数</a><a className="nav-link" href="/foundation-v20">程序构造</a><a className="nav-link" href="/mistakes">错题库</a><a className="nav-link" href="/">总览</a></div></header>

    <section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">V22 验收 {passed}/12</span><span className="scope-label">EXPERIMENT → TRANSITION → DIMENSION → CONSERVATION → PROOF</span></div><h1>系统从匿名实验中发现了第一组可证明物理程序</h1><p className="lede">训练输入只有 q0–q3 的有向有理计数器状态和实验前后值，不包含位置、速度、加速度、时间或动量名称。系统搜索可执行转移程序，在未见的负状态、多时间步世界中重放，并从程序结构反推量纲关系和守恒量。</p><div className="run-id"><span>LATEST</span><code>{report.run_id}</code><code>{acceptance.classification}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>5</strong><span>提升程序</span></div><p>4 个转移程序 + 1 个守恒程序</p></div></section>

    <section className="metric-grid meta-score-grid">
      <article className="metric-card accent-cyan"><p>匿名表达式搜索</p><strong>{discovery.expressions_generated}</strong><span>最多 5 个语法节点</span></article>
      <article className="metric-card accent-violet"><p>状态转移程序</p><strong>{discovery.channel_programs.length}</strong><span>四个通道全部覆盖</span></article>
      <article className="metric-card accent-amber"><p>密封多步重放</p><strong>{proofs.kinematics.hidden_replay.length}</strong><span>全部通过</span></article>
      <article className="metric-card accent-cyan"><p>非平凡守恒量</p><strong>1</strong><span>两个实际变化通道</span></article>
      <article className="metric-card accent-slate"><p>错误物理声明</p><strong>{acceptance.mutation_audits.length}</strong><span>全部被反例拒绝</span></article>
    </section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">OPAQUE INPUT</p><h2>学习器实际得到了什么</h2></div><span className="status-chip good">NO PHYSICS LABELS</span></div><div className="operator-discovery-grid"><article className="metric-card"><p>CHANNELS</p><strong className="operator-name">q0 · q1 · q2 · q3</strong><span>没有人类含义标签</span></article><article className="metric-card"><p>VALUES</p><strong className="operator-name">(P,N;D)</strong><span>V21 三计数器有向有理量</span></article><article className="metric-card"><p>OBSERVATIONS</p><strong className="operator-name">before → after</strong><span>{discovery.kinematic_training_cases} 条运动行 · {discovery.exchange_training_cases} 条交换行</span></article><article className="metric-card"><p>LANGUAGE</p><strong className="operator-name">READ · MERGE · TURN · SEM</strong><span>非 Transformer、非回归拟合</span></article></div></section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">DISCOVERED TRANSITION</p><h2>四个通道的可执行程序</h2></div><span className="status-chip good">UNIVERSALLY PROVED</span></div><div className="operator-discovery-grid">{discovery.channel_programs.map(item => <article className="metric-card" key={item.program_id}><p><code>{item.program_id}</code></p><strong className="operator-name">q{item.output_channel}′ = {item.opaque_program}</strong><span>{item.training_cases} training transitions</span><small>human law name: {String(item.human_law_name)}</small></article>)}</div><div className="posthoc-note"><span>证明后翻译</span><strong>x′=x+v·Δt；v′=v+a·Δt；a′=a；Δt′=Δt</strong><small>这是离散显式更新，不是连续微分方程。</small></div></section>

    <section className="content-grid operation-grid"><article className="surface comparison-card"><div className="section-heading"><div><p className="eyebrow">DIMENSION DISCOVERY</p><h2>量纲关系来自程序结构</h2></div><span className="status-chip good">NO UNIT NAMES GIVEN</span></div><div className="evidence-list">{discovery.dimension_constraints.map(item => <div className="evidence-row" key={item}><div><strong>{item}</strong><span>由 MERGE 同量纲与 SEM 量纲合成产生</span></div><b>PROVED</b></div>)}</div><div className="posthoc-note"><span>推导链</span><strong>{proofs.dimensions.derived_relation}</strong><small>选 D0=长度、D3=时间后，D1=速度、D2=加速度；该人类基底未给学习器。</small></div></article><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">CONSERVATION</p><h2>封闭交换中的不变量</h2></div></div><div className="receipt-list"><div><dt>program</dt><dd>{discovery.conservation.opaque_program}</dd></div><div><dt>changed channels</dt><dd>{discovery.conservation.changed_channels.join(", ")}</dd></div><div><dt>training cases</dt><dd>{discovery.conservation.case_count}</dd></div><div><dt>universal proof</dt><dd>{proofs.conservation.passed ? "通过" : "失败"}</dd></div></div><div className="posthoc-note"><span>证明后解释</span><strong>内部传递使一边增加、另一边减少，总量保持</strong><small>可解释为动量式守恒，但尚未引入质量和力。</small></div></article></section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">NORMALIZATION</p><h2>连续物理计算不会无限膨胀表示</h2></div></div><div className="operator-discovery-grid"><article className="metric-card"><p>01 / CANCEL</p><strong className="operator-name">正反公共计数器相消</strong><span>净值保持不变</span></article><article className="metric-card"><p>02 / EUCLID</p><strong className="operator-name">调用 V20 商余循环</strong><span>求幅值与分母的公共因子</span></article><article className="metric-card"><p>03 / REDUCE</p><strong className="operator-name">三个通道同步约分</strong><span>保持等价关系</span></article><article className="metric-card"><p>04 / FIXPOINT</p><strong className="operator-name">再次规范化不再改变</strong><span>{proofs.normalization.passed ? "证明通过" : "证明失败"}</span></article></div></section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">MISTAKE ROOM</p><h2>错误更新与错误守恒量</h2></div></div><div className="operator-discovery-grid">{acceptance.mutation_audits.map(item => <article className="metric-card" key={item.mutation}><p><code>{item.mutation}</code></p><strong className="operator-name">{item.rejected ? "已拒绝" : "未拒绝"}</strong><span>{item.counterexample?.world_id || "no counterexample"}</span><small>sealed experiment counterexample</small></article>)}</div></section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">STRICT OBLIGATIONS</p><h2>十二项物理发现验收</h2></div></div><div className="operator-discovery-grid">{acceptance.proof_obligations.map(item => <article className="metric-card" key={item.obligation_id}><p><code>{item.obligation_id}</code></p><strong className="operator-name">{item.passed ? "通过" : "失败"}</strong><span>独立证据</span></article>)}</div></section>

    <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">HONEST BOUNDARY</p><h2>这是第一层离散物理，不是完整经典力学</h2></div></div><ul>{acceptance.limitations.map(item => <li key={item}>{item}</li>)}</ul><div className="boundary-box"><p>准确成果</p><code>{report.claim.achieved}</code><span>未声称：{report.claim.not_claimed}</span></div><p className="digest-line">内容摘要 <code>{report.content_digest}</code></p></section>
  </main>;
}
