import reportData from "../../data/constraint_mechanics_v29_latest.json";
const r=reportData,a=r.acceptance,d=a.discovery,g=a.mechanics_capability_graph;
export default function Page(){return <main>
<header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">CONSTRAINT MECHANICS V29</p><p className="brand-name">AKGM-N0 / 约束投影与广义坐标</p></div></div><div className="run-meta"><a className="nav-link" href="/mechanics-v30">振动稳定性 V30</a><a className="nav-link" href="/mechanics-v28">连续动力学</a><a className="nav-link" href="/mechanics-v27">刚体力学</a><a className="nav-link" href="/">总览</a></div></header>
<section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">V29 验收 12/12</span><span className="scope-label">METRIC → TANGENT → PROJECT → COMPRESS → REBUILD</span></div><h1>系统把二维受约束状态压缩为一个可逆广义坐标</h1><p className="lede">学习器从81个度量、16个定向切向和4个投影候选中各选出唯一程序。投影后的状态满足约束微分条件，一个标量即可重建全部二维切向状态。</p><div className="run-id"><span>LATEST</span><code>{r.run_id}</code><code>{a.classification}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>{g.verified_domains}/{g.total_domains}</strong><span>力学领域</span></div><p>下一项：{g.next_selected_gap}</p></div></section>
<section className="metric-grid meta-score-grid"><article className="metric-card accent-cyan"><p>度量候选</p><strong>{d.metric_candidates_generated}</strong><span>唯一选出</span></article><article className="metric-card accent-violet"><p>切向候选</p><strong>{d.tangent_candidates_generated}</strong><span>唯一选出</span></article><article className="metric-card accent-amber"><p>投影候选</p><strong>{d.projection_candidates_generated}</strong><span>唯一选出</span></article><article className="metric-card accent-cyan"><p>自由度</p><strong>{d.ambient_state_coordinate_count}→{d.generalized_coordinate_count}</strong><span>可逆重建</span></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">DISCOVERED PROGRAMS</p><h2>匿名约束闭环</h2></div></div><div className="operator-discovery-grid"><article className="metric-card"><p>METRIC</p><strong className="operator-name"><code>{d.selected_metric.opaque_program}</code></strong><span>人类翻译：x₁y₁+x₂y₂</span></article><article className="metric-card"><p>TANGENT</p><strong className="operator-name"><code>{d.selected_tangent.opaque_program}</code></strong><span>人类翻译：(-y,x)</span></article><article className="metric-card"><p>PROJECT</p><strong className="operator-name"><code>{d.selected_projection.opaque_program}</code></strong><span>移除归一化径向分量</span></article></div></section>
<section className="content-grid operation-grid"><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">CONSTRAINT</p><h2>约束微分</h2></div></div><div className="posthoc-note"><strong>x²+y²=R²</strong><small>状态必须满足 xvₓ+yvᵧ=0。</small></div></article><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">GENERALIZED STATE</p><h2>一维参数化</h2></div></div><div className="posthoc-note"><strong>v=s(-y,x)</strong><small>s 由度量投影获得，并能精确重建 v。</small></div></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">COMPLETENESS GATE</p><h2>9/15，继续 M10</h2></div></div><div className="boundary-box"><p>下一研究缺口</p><code>{g.next_selected_gap}</code><span>{g.selection_reason}</span></div><ul>{a.limitations.map(i=><li key={i}>{i}</li>)}</ul></section>
</main>}
