import data from "../../data/interventional_science_v38_latest.json";
const r=data,a=r.acceptance,d=a.discovery,m=a.dataset.metadata,f=a.future_batch_audit,c=a.claim_state,g=a.discovery_gates,n=a.repeatability_audit;
const gateRows=[
  ["真实受控实验",g.real_controlled_experiment],["独立数据进程",g.separate_data_process],
  ["承诺早于第二批",g.commit_before_second_batch],["干预确定方向",g.causal_direction_from_intervention],
  ["机制复杂度选择",g.mechanism_complexity_selected],["未见负载预测",g.unseen_intervention_prediction],
  ["重复噪声测量",g.repeatability_noise_measured],["单调形状证明",g.monotone_shape_certificate],
  ["替代图被反驳",g.alternative_graphs_falsified],["已知校准匹配",g.known_calibration_match],
  ["干预顺序随机化",g.randomized_intervention_order],["漂移已分离",g.drift_separated],
  ["实时新干预",g.live_new_intervention],["人类新颖性",g.human_novelty],
];
export default function Page(){return <main><header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">INTERVENTIONAL SCIENCE V38</p><p className="brand-name">AKGM-N0 / 受控输入、因果方向与漂移门控</p></div></div><div className="run-meta"><a className="nav-link" href="/science-v39">在线实验 V39</a><a className="nav-link" href="/science-v37">真实档案 V37</a><a className="nav-link" href="/science-v36">发现门控</a><a className="nav-link" href="/">总览</a></div></header>
<section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">V38 验收 15/15</span><span className="scope-label">CONTROL → RESPOND → ORIENT → COMMIT → REPEAT → DRIFT-GATE</span></div><h1>系统从真实受控实验中确定方向并选择响应机制</h1><p className="lede">NIST 对负载传感器施加已知输入并记录响应。系统只获得匿名“受控槽位”，让正向、反向和无连接图竞争；第二实验批次在模型承诺后才揭晓。</p><div className="run-id"><span>LATEST</span><code>{r.run_id}</code><code>{a.classification}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>{c.interventional_pipeline_verified?"PASS":"BLOCK"}</strong><span>干预管线</span></div><p>无漂移因果效应：仍阻断</p></div></section>
<section className="metric-grid meta-score-grid"><article className="metric-card accent-cyan"><p>实验记录</p><strong>{m.rows}</strong><span>{m.experimental_batches} 个批次</span></article><article className="metric-card accent-violet"><p>候选机制</p><strong>{d.candidate_count}</strong><span>3 图 × 多项式</span></article><article className="metric-card accent-amber"><p>未见干预</p><strong>{f.unseen_intervention_count}</strong><span>第二批密封预测</span></article><article className="metric-card accent-cyan"><p>第二批 MAPE</p><strong>{(f.median_absolute_percentage_error*100).toFixed(3)}%</strong><span>RMSE {f.root_mean_square_error.toExponential(2)}</span></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">DISCOVERED MECHANISM</p><h2>匿名干预响应程序</h2></div></div><div className="operator-discovery-grid"><article className="metric-card"><p>CAUSAL GRAPH</p><strong className="operator-name">{d.selected_mechanism.direction}</strong><span>Q0 被施加，Q1 随后测量</span></article><article className="metric-card"><p>COMPLEXITY</p><strong className="operator-name">DEGREE {d.selected_mechanism.degree}</strong><span>BIC 优势 {d.bic_margin.toFixed(3)}</span></article><article className="metric-card"><p>OPAQUE PROGRAM</p><strong className="operator-name" style={{minWidth:0}}><code style={{fontSize:"0.72rem",overflowWrap:"anywhere",whiteSpace:"normal"}}>{d.selected_mechanism.opaque_program}</code></strong><span>二次校准响应</span></article></div></section>
<section className="content-grid operation-grid"><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">REPEATABILITY</p><h2>两批同级输入</h2></div></div><div className="posthoc-note"><strong>σΔ={n.repeatability_standard_deviation.toExponential(3)}</strong><small>{n.paired_levels} 个配对负载；平均绝对批差 {n.mean_absolute_batch_difference.toExponential(3)}。</small></div></article><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">DIRECTION</p><h2>相关不负责定向</h2></div></div><div className="posthoc-note"><strong>do(Q0) → observe(Q1)</strong><small>反向模型即使能拟合，也与实验施加角色不兼容。</small></div></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">CAUSAL GATES</p><h2>方向通过，纯净效应仍受漂移阻断</h2></div></div><div className="operator-discovery-grid">{gateRows.map(([name,passed])=><article className="metric-card" key={String(name)}><p>{name}</p><strong className="operator-name">{passed?"PASS":"BLOCKED"}</strong><span>{passed?"证据已登记":"禁止升级声明"}</span></article>)}</div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">CLAIM BOUNDARY</p><h2>历史校准实验，不是新因果定律</h2></div></div><div className="boundary-box"><p>当前标签</p><code>{c.current_label}</code><span>两批负载都按递增顺序施加，时间漂移无法与响应完全分离。</span></div><ul>{a.limitations.map(i=><li key={i}>{i}</li>)}</ul></section></main>}
