import type { Metadata } from "next";
import reportData from "../../data/metamachine_gen2_five_control_latest.json";

export const metadata: Metadata = { title: "第二批五个控制公式 · AKGM-N0", description: "五种新控制机制的发现、验证与归档报告。" };

type Candidate = { rank: number; candidate_id: string; fit_error: number; disposition: string; mistake_id: string | null; program: { words: number[] } };
type Round = { round_index: number; active_case_indices: number[]; candidate: Candidate; added_counterexample_index: number | null; programs_generated: number };
type Task = { opaque_task: string; mechanism: string; candidate: Candidate; cegis: { round_count: number; rounds: Round[] }; sealed_results: Array<{ passed: boolean }>; adversarial_results: Array<{ passed: boolean }>; input_width: number; mechanism_evidence: { grow_operand: number; jump_count: number }; success_room_record: { room_record_id: string; operation_id: string } };
type Report = { run_id: string; created_at: string; architecture: string; knowledge_status: string; stop_rule: { actual: number; satisfied: boolean }; tasks: Task[]; five_candidate_feedback_per_task: Record<string, Candidate[]>; gates: Array<{ gate_id: string; passed: boolean }>; success_room_active_count: number; mistake_feedback_count: number; ledger_event_count: number; autonomy_accounting: { host_supplied: string[]; learner_selected: string[]; posthoc_only: string[] }; limitations: string[] };

const report = reportData as Report;
const copy: Record<string, { title: string; formula: string; logic: string }> = {
  j: { title: "双状态减法振荡", formula: "(a,b)₀=(0,0)；(a,b)←(a+b,1−a) → 0,1,1,0,−1,−1…", logic: "两个旧状态同步生成两个新状态，形成带负值的六步循环。" },
  k: { title: "三级依赖级联", formula: "(a,b,c)←(a+b,b+c,c+1) → 0,0,0,1,4,10…", logic: "三个状态构成单向累积链；事后可解释为三阶组合结构。" },
  l: { title: "阈值回绕控制", formula: "s←s+1；若达到 4，则 s←s−4 → n mod 4", logic: "没有余数指令；候选自己选择比较、负值分支和回绕路径。" },
  m: { title: "双输入比较改写", formula: "较大状态←较大状态−较小状态，直到相等 → gcd(a,b)", logic: "两个输入驱动不定长循环，同时使用零分支和负值分支。" },
  n: { title: "变化步长守卫", formula: "r←r−d；d←d+2；c←c+1 → ⌊√n⌋", logic: "下一次减法将越过零时自主停止；没有平方根指令。" },
};

function Feedback({ task }: { task: Task }) {
  const items = report.five_candidate_feedback_per_task[`opaque_task_${task.opaque_task}`];
  return <article className="surface promotion-card"><div className="section-heading"><div><p className="eyebrow">TASK {task.opaque_task.toUpperCase()} · FIVE PROGRAMS</p><h2>{copy[task.opaque_task].title}</h2></div><span className="evidence-chip">1 成功 / 4 错题</span></div><div className="task-table"><div className="task-row task-header"><span>候选</span><span>长度</span><span>误差</span><span>归档</span></div>{items.map((item) => <div className="task-row" key={item.candidate_id}><code>#{item.rank} {item.candidate_id}</code><span>{item.program.words.length} words</span><strong className={item.fit_error === 0 ? "zero-value" : ""}>{item.fit_error.toFixed(3)}</strong><span>{item.disposition === "success_room" ? "成功公式房间" : `错题库 ${item.mistake_id}`}</span></div>)}</div></article>;
}

export default function FiveControlPage() {
  const generatedAt = new Date(report.created_at).toLocaleString("zh-CN", { hour12: false });
  const exact = report.tasks.reduce((sum, task) => sum + [...task.sealed_results, ...task.adversarial_results].filter((item) => item.passed).length, 0);
  return <main>
    <header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">C5</span><div><p className="eyebrow">SECOND FIVE-SUCCESS GATE</p><p className="brand-name">AKGM-N0 / MetaMachine Gen 2</p></div></div><div className="run-meta"><a className="nav-link" href="/universal-proof">全域证明</a><a className="nav-link" href="/gen2-five">第一批五公式</a><a className="nav-link" href="/mistakes">错题库</a><a className="nav-link" href="/">总览</a><span className="meta-dot" /><span>{generatedAt}</span></div></header>
    <section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">第二批五个新公式通过</span><span className="scope-label">{report.knowledge_status}</span></div><h1>从固定递推继续走向比较、阈值和数据驱动停止</h1><p className="lede">五个赢家不仅行为不同：它们分别使用双状态振荡、三级级联、阈值回绕、双输入比较改写和变化步长守卫。所有数学名称均为验证后的解释。</p><div className="run-id"><span>RUN</span><code>{report.run_id}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>5/5</strong><span>第二批停止门满足</span></div><p>{exact}/40 SEALED + ADVERSARIAL</p></div></section>
    <section className="metric-grid"><article className="metric-card accent-cyan"><p>新成功程序</p><strong>5</strong><span>与旧 18 条行为去重</span></article><article className="metric-card accent-violet"><p>成功房间</p><strong>{report.success_room_active_count}</strong><span>18 → 23</span></article><article className="metric-card accent-amber"><p>候选反馈</p><strong>25</strong><span>5 成功 · {report.mistake_feedback_count} 错题</span></article><article className="metric-card accent-slate"><p>反例轮次</p><strong>{report.tasks.reduce((sum, task) => sum + task.cegis.round_count, 0)}</strong><span>同一搜索器</span></article></section>
    <section className="content-grid operation-grid">{report.tasks.map((task) => <article className="surface concept-card" key={task.opaque_task}><div className="section-heading"><div><p className="eyebrow">OPAQUE TASK {task.opaque_task.toUpperCase()}</p><h2>{copy[task.opaque_task].title}</h2></div><span className="status-pill">8/8 EXACT</span></div><div className="posthoc-note"><span>{task.candidate.candidate_id}</span><strong>{copy[task.opaque_task].formula}</strong><small>{copy[task.opaque_task].logic}</small></div><div className="finding-strip"><span className="note-icon">✓</span><p>{task.success_room_record.room_record_id} · {task.success_room_record.operation_id} · width {task.input_width} · grow {task.mechanism_evidence.grow_operand} · jump {task.mechanism_evidence.jump_count}</p></div></article>)}</section>
    <section className="surface promotion-card"><div className="section-heading"><div><p className="eyebrow">COUNTEREXAMPLE REVISION</p><h2>9 轮结构修正</h2></div><span className="evidence-chip">SAME SEARCH INSTANCE</span></div><div className="task-table"><div className="task-row task-header"><span>任务 / 轮次</span><span>活动证据</span><span>候选</span><span>反馈</span></div>{report.tasks.flatMap((task) => task.cegis.rounds.map((round) => <div className="task-row" key={`${task.opaque_task}-${round.round_index}`}><code>{task.opaque_task.toUpperCase()} · ROUND {round.round_index + 1}</code><span>[{round.active_case_indices.join(", ")}] · {round.programs_generated} programs</span><span>{round.candidate.candidate_id}</span><span>{round.added_counterexample_index === null ? "精确收敛" : `加入反例 #${round.added_counterexample_index}`}</span></div>))}</div></section>
    <section className="content-grid operation-grid">{report.tasks.map((task) => <Feedback task={task} key={`feedback-${task.opaque_task}`} />)}</section>
    <section className="content-grid lower-grid"><article className="surface task-table-card"><div className="section-heading"><div><p className="eyebrow">AUTONOMY ACCOUNTING</p><h2>谁决定了什么</h2></div></div><div className="promotion-lanes"><div className="promotion-lane"><span>宿主提供</span>{report.autonomy_accounting.host_supplied.map((item) => <p key={item}>• {item}</p>)}</div><div className="promotion-lane"><span>学习器选择</span>{report.autonomy_accounting.learner_selected.map((item) => <p key={item}>• {item}</p>)}</div><div className="promotion-lane blocked-lane"><span>仅事后解释</span>{report.autonomy_accounting.posthoc_only.map((item) => <p key={item}>• {item}</p>)}</div></div></article><article className="surface gates-section"><div className="section-heading"><div><p className="eyebrow">STOP GATES</p><h2>全部资格门</h2></div></div><div className="gate-grid">{report.gates.map((gate) => <div className="gate-item" key={gate.gate_id}><span className={`gate-light ${gate.passed ? "passed" : "failed"}`} /><div><strong>{gate.gate_id}</strong><span>{gate.passed ? "通过" : "未通过"}</span></div></div>)}</div></article></section>
    <section className="surface standalone-limitations"><div className="section-heading"><div><p className="eyebrow">HONEST BOUNDARY</p><h2>仍然不能夸大的部分</h2></div></div><ul className="limitations-list">{report.limitations.map((item, index) => <li key={item}><span>0{index + 1}</span><p>{item}</p></li>)}</ul></section>
    <footer><div><span className="footer-mark">AKGM-N0</span><span>比较 · 阈值 · 数据驱动停止 · 五成功门</span></div><code>{report.architecture} · ledger {report.ledger_event_count}</code></footer>
  </main>;
}
