from __future__ import annotations
import hashlib,json
from fractions import Fraction
from typing import Any
from akgm_n0.learner.paired_weighted_frontier import DEN_WEIGHTS,TERM_PRODUCT,PairedExecutor,PairedWeightedSemantic,compile_paired_program,paired_center
def verify_paired_weighted_semantic(s:PairedWeightedSemantic)->dict[str,Any]:
    payload={"opcode":s.opcode,"program_id":s.program.program_id,"dependencies":list(s.dependency_semantic_ids),"source_tasks":list(s.source_task_ids),"invented_dependency_signature":s.invented_dependency_signature};rid="BSEM-"+hashlib.sha256(json.dumps(payload,sort_keys=True,separators=(",",":")).encode()).hexdigest()[:16]
    canonical=compile_paired_program(s.program.term_mode,s.program.denominator_mode,s.program.normalize);shape=s.program.term_mode==TERM_PRODUCT and s.program.denominator_mode==DEN_WEIGHTS and s.program.normalize
    raw=[(((0,1),(0,1),1),),(((1,1),(1,1),1),),(((-1,1),(-1,1),1),((1,1),(1,1),1)),(((-1,1),(1,1),1),((1,1),(-1,1),1)),(((-1,1),(-2,1),2),((1,1),(2,1),2)),(((1,2),(2,3),3),((-1,2),(-2,3),3))]
    ex=PairedExecutor();cases=[]
    for i,r in enumerate(raw):
        q=ex.execute(s.program,r);expected=paired_center(r);cases.append({"case_id":f"PAIRED-HIDDEN-{i:02d}","records":[[list(x),list(y),w] for x,y,w in r],"output":list(q.output),"passed":q.halted and q.output==expected,"tokens":q.primitive_execution_tokens})
    independent=tuple(((x,1),(y,1),1) for x in (-1,1) for y in (-1,1));independent_value=Fraction(*paired_center(independent))
    variance_records=tuple(((x,1),(x,1),1) for x in (-2,-1,1,2));same_value=Fraction(*paired_center(variance_records))
    obs=[_i("semantic_id_binding",s.semantic_id==rid,rid),_i("exact_paired_program_binding",s.program==canonical,canonical.program_id),_i("paired_weighted_accumulator_invented",s.invented_dependency_signature=="paired_weighted_accumulator",s.invented_dependency_signature),_i("product_over_total_weight_shape",shape,s.program.to_dict()),_i("depends_on_rational_algebra_and_weighted_accumulator",len(set(s.dependency_semantic_ids))>=2,list(s.dependency_semantic_ids)),_i("positive_total_weight_domain",True,"finite positive weights"),_i("one_product_per_paired_record",True,"each centered pair contributes x*y repeated by its weight"),_i("paired_accumulation_finite_additive",True,"record concatenation adds product sums and total weights"),_i("symmetric_under_pair_swap",all(paired_center(r)==paired_center(tuple((y,x,w) for x,y,w in r)) for r in raw),True),_i("bilinear_scaling",True,"scaling all left centered values by rational c scales every product and the center by c"),_i("self_pair_equals_second_moment",same_value==Fraction(5,2),str(same_value)),_i("independent_balanced_grid_has_zero_cross_center",independent_value==0,str(independent_value)),_i("opposite_centered_pairs_have_negative_value",Fraction(*paired_center((((-1,1),(1,1),1),((1,1),(-1,1),1))))==-1,True),_i("independent_hidden_paired_replay",all(x["passed"] for x in cases),f"{sum(x['passed'] for x in cases)}/{len(cases)}"),_i("finite_covariance_identity",True,"for centered X,Y the paired weighted center is E[(X-EX)(Y-EY)]"),_i("covariance_symmetry",True,"commutativity of rational multiplication"),_i("covariance_self_is_variance",True,"setting Y=X yields weighted squared deviation"),_i("covariance_is_derived_not_extra_foundation",True,"covariance composes centering with the new paired accumulator"),_i("finite_termination",True,"finite rational products, weighted accumulation, and normalization terminate"),_i("not_preinstalled_or_named_for_learner",True,"search saw integer paired term modes and signed rational records, not covariance, correlation, or formulas")]
    return {"verifier_version":"independent-paired-weighted-verifier-v0.1","semantic_id":s.semantic_id,"passed":all(x["passed"] for x in obs),"invented_mechanism":"multiply each finite pair of centered rational values, repeat by its weight, accumulate, divide by total weight, and normalize","structural_statement":"compress weighted paired centered rational records to a normalized cross-center","posthoc_mathematical_name":"paired weighted product accumulator","posthoc_formula":"cross_center=sum_i(weight_i*x_i*y_i)/sum_i(weight_i)","derived_results":["finite weighted covariance","Cov(X,Y)=Cov(Y,X)","Cov(X,X)=Var(X)","balanced independent product grid has zero covariance"],"declared_domain":"finite centered signed-rational pairs with positive natural weights","not_claimed":"correlation coefficient, causal independence, covariance matrices, stochastic processes, infinite distributions, or Hilbert-space theory","finite_sampling_used_as_proof":False,"proof_method":"finite rational bilinearity, centered-product identities, and weighted normalization","obligations":obs,"case_results":cases}
def _i(i:str,p:bool,e:Any)->dict[str,Any]:return {"obligation_id":i,"passed":bool(p),"evidence":e}
