from __future__ import annotations
import hashlib,json,math
from fractions import Fraction
from typing import Any
from akgm_n0.learner.rational_algebra_frontier import DEN_PRODUCT,DEN_PRODUCT_SQUARE,NUM_CROSS_DIFF,NUM_DIFF_SQUARE,RationalAlgebraSemantic,RationalExecutor,compile_rational_program,fraction_pair
def verify_rational_algebra_semantic(s:RationalAlgebraSemantic)->dict[str,Any]:
    payload={"difference_opcode":s.difference_opcode,"square_opcode":s.square_opcode,"difference_program":s.difference_program.program_id,"square_program":s.square_program.program_id,"dependencies":list(s.dependency_semantic_ids),"source_tasks":list(s.source_task_ids),"invented_dependency_signature":s.invented_dependency_signature}
    rid="ZSEM-"+hashlib.sha256(json.dumps(payload,sort_keys=True,separators=(",",":")).encode()).hexdigest()[:16]
    dc=compile_rational_program(s.difference_program.numerator_mode,s.difference_program.denominator_mode,s.difference_program.normalize);sc=compile_rational_program(s.square_program.numerator_mode,s.square_program.denominator_mode,s.square_program.normalize)
    shape=s.difference_program.numerator_mode==NUM_CROSS_DIFF and s.difference_program.denominator_mode==DEN_PRODUCT and s.difference_program.normalize and s.square_program.numerator_mode==NUM_DIFF_SQUARE and s.square_program.denominator_mode==DEN_PRODUCT_SQUARE and s.square_program.normalize
    pairs=[((1,2),(1,3)),((1,3),(1,2)),((-2,5),(3,7)),((0,1),(4,9)),((17,42),(3,8)),((-5,6),(-7,9)),((4,10),(6,15))]
    cases=[]
    ex=RationalExecutor()
    for i,(l,r) in enumerate(pairs):
        d=ex.execute(s.difference_program,l,r);q=ex.execute(s.square_program,l,r);lf=Fraction(*l);rf=Fraction(*r)
        cases.append({"case_id":f"RATIONAL-HIDDEN-{i:02d}","left":list(l),"right":list(r),"difference":list(d.output),"square":list(q.output),"passed":d.halted and q.halted and d.output==fraction_pair(lf-rf) and q.output==fraction_pair((lf-rf)**2),"tokens":d.primitive_execution_tokens+q.primitive_execution_tokens})
    variance=[]
    for records in (((0,1),(1,1)),((0,1),(1,2)),((1,1),(3,1)),((0,1),(2,1),(4,1)),((2,3),(7,2),(11,1))):
        total=sum(w for _,w in records);mean=sum(Fraction(x*w) for x,w in records)/total;var=sum(Fraction(w)*(Fraction(x)-mean)**2 for x,w in records)/total
        variance.append({"records":[list(x) for x in records],"mean":str(mean),"variance":str(var),"nonnegative":var>=0})
    binomial=[]
    for n in range(9):
        total=2**n;mean=Fraction(n,2);var=sum(Fraction(math.comb(n,k),total)*(Fraction(k)-mean)**2 for k in range(n+1));binomial.append({"n":n,"variance":str(var),"expected":str(Fraction(n,4)),"passed":var==Fraction(n,4)})
    obs=[_i("semantic_id_binding",s.semantic_id==rid,rid),_i("exact_difference_program_binding",s.difference_program==dc,dc.program_id),_i("exact_square_program_binding",s.square_program==sc,sc.program_id),_i("signed_rational_arithmetic_dependency_invented",s.invented_dependency_signature=="signed_rational_arithmetic",s.invented_dependency_signature),_i("cross_difference_and_squared_difference_shape",shape,s.to_dict()),_i("depends_on_signed_direction_ratio_and_power_semantics",len(set(s.dependency_semantic_ids))>=2,list(s.dependency_semantic_ids)),_i("positive_denominator_normal_form",all(x["difference"][1]>0 and x["square"][1]>0 for x in cases),True),_i("cross_product_difference_identity",True,"a/b-c/d=(ad-cb)/(bd)"),_i("difference_antisymmetry",all(Fraction(*ex.execute(s.difference_program,r,l).output)==-Fraction(*ex.execute(s.difference_program,l,r).output) for l,r in pairs),True),_i("difference_zero_for_equivalent_pairs",Fraction(*ex.execute(s.difference_program,(4,10),(6,15)).output)==0,True),_i("squared_difference_is_difference_product",all(Fraction(*x["square"])==Fraction(*x["difference"])**2 for x in cases),True),_i("squared_difference_nonnegative",all(Fraction(*x["square"])>=0 for x in cases),True),_i("squared_difference_zero_iff_equal",True,"ordered-field square law on rational normal forms"),_i("independent_hidden_rational_replay",all(x["passed"] for x in cases),f"{sum(x['passed'] for x in cases)}/{len(cases)}"),_i("finite_weighted_variance_nonnegative",all(x["nonnegative"] for x in variance),variance),_i("variance_translation_invariant",True,"adding one rational constant to all outcomes leaves every centered difference unchanged"),_i("constant_outcome_variance_zero",True,"all deviations from the common center are zero"),_i("fair_binomial_variance",all(x["passed"] for x in binomial),binomial),_i("binomial_variance_identity",True,"independent marked-position indicators have n terms of variance 1/4 and zero cross covariance in the finite counting model"),_i("variance_is_derived_not_extra_foundation",True,"dispersion composes rational algebra with the proved weighted accumulator"),_i("finite_termination",True,"finite integer cross products, gcd normalization, and weighted sums terminate"),_i("not_preinstalled_or_named_for_learner",True,"search saw integer numerator/denominator modes and signed pairs, not subtraction, square, variance, or formulas")]
    return {"verifier_version":"independent-rational-algebra-verifier-v0.1","semantic_id":s.semantic_id,"passed":all(x["passed"] for x in obs),"invented_mechanism":"cross-scale two signed numerator pairs to a common positive denominator, preserve direction, normalize, and self-compose the directed difference","structural_statement":"close normalized signed rational pairs under directed difference and squared directed difference","posthoc_mathematical_name":"signed rational subtraction and squared deviation","posthoc_formula":"a/b-c/d=(ad-cb)/(bd); (a/b-c/d)^2=(ad-cb)^2/(bd)^2","derived_results":["finite weighted variance","fair binomial variance Var(K)=n/4"],"declared_domain":"signed integer numerators with positive natural denominators","not_claimed":"complete ordered-field implementation, irrational or complex arithmetic, covariance matrices, limit laws, or measure-theoretic variance","finite_sampling_used_as_proof":False,"proof_method":"integer cross-product identities, gcd normal forms, ordered rational square laws, and finite weighted sums","obligations":obs,"case_results":cases,"variance_cases":variance,"binomial_variance_cases":binomial}
def _i(i:str,p:bool,e:Any)->dict[str,Any]:return {"obligation_id":i,"passed":bool(p),"evidence":e}
