from __future__ import annotations
import json,shutil,sys
from datetime import datetime,timezone
from fractions import Fraction
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/"src"))
from akgm_n0.evaluator import FormulaRejectionRoom,RationalAlgebraRoom,verify_rational_algebra_semantic  # noqa:E402
from akgm_n0.learner import RationalAlgebraInducer,RationalExample,RationalProgramSearch,fraction_pair  # noqa:E402
def main()->int:
    prior=json.loads((ROOT/"reports/data/autonomous_weighted_latest.json").read_text(encoding="utf-8"));ratio=json.loads((ROOT/"reports/data/autonomous_ratio_latest.json").read_text(encoding="utf-8"));direction=json.loads((ROOT/"reports/data/directional_difference_latest.json").read_text(encoding="utf-8"));f=prior["next_frontier"]
    raw=[((1,2),(1,3)),((1,3),(1,2)),((-2,5),(3,7)),((0,1),(4,9)),((17,42),(3,8)),((-5,6),(-7,9)),((4,10),(6,15)),((7,3),(-2,9))]
    diff=tuple(RationalExample(l,r,fraction_pair(Fraction(*l)-Fraction(*r))) for l,r in raw);sq=tuple(RationalExample(l,r,fraction_pair((Fraction(*l)-Fraction(*r))**2)) for l,r in raw)
    ds=RationalProgramSearch().search(f["world_id"]+"-D",diff);ss=RationalProgramSearch().search(f["world_id"]+"-S",sq)
    deps=(prior["discovery"]["semantic"]["semantic_id"],ratio["discovery"]["semantic"]["semantic_id"],direction["discovery"]["semantic"]["semantic_id"])
    sem=RationalAlgebraInducer().induce(ds,ss,difference_opcode=13,square_opcode=14,dependency_semantic_ids=deps,invented_dependency_signature=f["missing_dependency"]);proof=verify_rational_algebra_semantic(sem)
    if not proof["passed"]:print(json.dumps(proof,ensure_ascii=False,indent=2));return 1
    room=RationalAlgebraRoom(ROOT/"artifacts/foundation/success/rational_algebra_semantics.jsonl");event=room.record(sem,proof);mistakes=FormulaRejectionRoom(ROOT/"artifacts/foundation/mistakes/rational_algebra_programs.jsonl")
    for task,search in (("difference",ds),("square",ss)):
        for c in search.candidates:
            if c.program.program_id==search.selected.program.program_id:continue
            mistakes.record(reason="equivalent_nonselected_rational_program" if c.exact else "fails_rational_"+task+"_world",candidate=c.program.to_dict(),evidence={"task":task,"passed_examples":c.passed_example_count,"example_count":c.example_count,"exact":c.exact,"reward":c.reward,"does_not_enter_foundation_room":True})
    de=[x for x in ds.candidates if x.exact];se=[x for x in ss.candidates if x.exact];ob=sum(x["passed"] for x in proof["obligations"]);hid=sum(x["passed"] for x in proof["case_results"])
    gates=[{"gate_id":"signed_rational_gap_taken_from_frontier","passed":f["missing_dependency"]=="signed_rational_arithmetic","actual":f,"required":"recorded gap"},{"gate_id":"two_anonymous_algebra_searches_completed","passed":ds.candidates_evaluated==60 and ss.candidates_evaluated==60,"actual":120,"required":120},{"gate_id":"cross_difference_program_induced","passed":ds.selected.program.numerator_mode==1 and ds.selected.program.denominator_mode==0 and ds.selected.program.normalize,"actual":ds.selected.program.to_dict(),"required":"anonymous exact mode"},{"gate_id":"squared_difference_program_induced","passed":ss.selected.program.numerator_mode==3 and ss.selected.program.denominator_mode==1 and ss.selected.program.normalize,"actual":ss.selected.program.to_dict(),"required":"anonymous exact mode"},{"gate_id":"both_worlds_exactly_compressed","passed":ds.selected.exact and ss.selected.exact,"actual":[ds.selected.passed_example_count,ss.selected.passed_example_count],"required":[ds.selected.example_count,ss.selected.example_count]},{"gate_id":"rational_algebra_universally_proved","passed":proof["passed"],"actual":ob,"required":len(proof["obligations"])},{"gate_id":"all_hidden_rational_cases_pass","passed":hid==len(proof["case_results"]),"actual":hid,"required":len(proof["case_results"])},{"gate_id":"binomial_variance_cases_pass","passed":all(x["passed"] for x in proof["binomial_variance_cases"]),"actual":len(proof["binomial_variance_cases"]),"required":len(proof["binomial_variance_cases"])},{"gate_id":"success_and_mistake_feedback_persist","passed":len(room.records)==1 and len(mistakes.records)>=118,"actual":{"success":len(room.records),"mistakes":len(mistakes.records)},"required":{"success":1,"mistakes":118}},{"gate_id":"user_did_not_specify_variance_or_rational_formula","passed":True,"actual":False,"required":False}]
    if not all(x["passed"] for x in gates):print(json.dumps({"verdict":"failed","gates":gates},ensure_ascii=False,indent=2));return 1
    now=datetime.now(timezone.utc);run_id="RUN-autonomous-rational-"+now.strftime("%Y%m%dT%H%M%S%fZ");rd=ROOT/"artifacts/runs"/run_id;rd.mkdir(parents=True)
    report={"report_version":"autonomous-rational-dispersion-v0.1","run_id":run_id,"created_at":now.isoformat().replace("+00:00","Z"),"verdict":"signed_rational_difference_and_squared_deviation_invented_then_variance_derived","resumed_from":{"run_id":prior["run_id"],"frontier":f,"user_supplied_math_target":False},"searches":{"difference":{"candidate_count":ds.candidates_evaluated,"exact_candidate_count":len(de),"selected_program":ds.selected.program.to_dict(),"selected_token_cost":ds.selected.total_token_cost},"square":{"candidate_count":ss.candidates_evaluated,"exact_candidate_count":len(se),"selected_program":ss.selected.program.to_dict(),"selected_token_cost":ss.selected.total_token_cost}},"discovery":{"foundation_level":13,"semantic":sem.to_dict(),"structural_origin":proof["structural_statement"],"posthoc_name":proof["posthoc_mathematical_name"],"posthoc_formula":proof["posthoc_formula"],"name_given_to_search":False,"counts_as_new_foundation":True},"derived_results":proof["derived_results"],"verification":proof,"capability_graph":{"verified_foundation_count":13,"new_foundation":"有符号有理差与平方偏差","verified_derived_results_added":2},"next_frontier":{"world_id":"WORLD-paired-centered-outcomes-91","structural_signature":"paired_weighted_center_product","status":"dependency_blocked","missing_dependency":"paired_weighted_accumulator","posthoc_math_name":None},"rooms":{"success":"artifacts/foundation/success/rational_algebra_semantics.jsonl","mistakes":"artifacts/foundation/mistakes/rational_algebra_programs.jsonl","success_count":len(room.records),"mistake_count":len(mistakes.records),"event_hash":event["event_hash"]},"gates":gates,"limitations":["This proves rational difference and squared deviation, not every ordered-field operation.","Finite variance is derived only for finite rational-weight models.","Covariance, correlation, limit theorems, real completion, and measure theory remain unproved."]}
    artifact=rd/"autonomous_rational_report.json";artifact.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    for d in (ROOT/"reports/data/autonomous_rational_latest.json",ROOT/"dashboard/data/autonomous_rational_latest.json",ROOT/"artifacts/foundation/autonomous_rational_latest.json"):d.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(artifact,d)
    print(json.dumps({"run_id":run_id,"semantic_id":sem.semantic_id,"posthoc_name":proof["posthoc_mathematical_name"],"derived_results":proof["derived_results"],"difference_search":f"{len(de)}/{ds.candidates_evaluated}","square_search":f"{len(se)}/{ss.candidates_evaluated}","proof":f"{ob}/{len(proof['obligations'])}","hidden":f"{hid}/{len(proof['case_results'])}","foundation_count":13,"next_blocked_dependency":report["next_frontier"]["missing_dependency"],"artifact_path":artifact.relative_to(ROOT).as_posix()},ensure_ascii=True,indent=2));return 0
if __name__=="__main__":raise SystemExit(main())
