from __future__ import annotations
import json,shutil,sys
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/"src"))
from akgm_n0.evaluator import FormulaRejectionRoom,WeightedFrontierRoom,verify_weighted_foundation_semantic  # noqa:E402
from akgm_n0.learner import WeightedAccumulatorSearch,WeightedExample,WeightedSemanticInducer,weighted_center  # noqa:E402
def main()->int:
    prior=json.loads((ROOT/"reports/data/autonomous_joint_latest.json").read_text(encoding="utf-8"));ratio=json.loads((ROOT/"reports/data/autonomous_ratio_latest.json").read_text(encoding="utf-8"));nested=json.loads((ROOT/"reports/data/nested_arithmetic_latest.json").read_text(encoding="utf-8"));f=prior["next_frontier"]
    raw=[((0,1),),((7,1),),((1,1),(3,1)),((1,2),(4,1)),((0,3),(5,2)),((2,3),(7,4),(11,1)),((3,5),(9,5)),((1,1),(2,2),(3,3),(4,4))]
    examples=tuple(WeightedExample(tuple(r),weighted_center(r)) for r in raw);search=WeightedAccumulatorSearch().search(f["world_id"],examples)
    deps=(ratio["discovery"]["semantic"]["semantic_id"],nested["discoveries"][0]["semantic"]["semantic_id"])
    semantic=WeightedSemanticInducer().induce(search,opcode=12,dependency_semantic_ids=deps,invented_dependency_signature=f["missing_dependency"]);proof=verify_weighted_foundation_semantic(semantic)
    if not proof["passed"]:print(json.dumps(proof,ensure_ascii=False,indent=2));return 1
    room=WeightedFrontierRoom(ROOT/"artifacts/foundation/success/weighted_frontier_semantics.jsonl");event=room.record(semantic,proof);mistakes=FormulaRejectionRoom(ROOT/"artifacts/foundation/mistakes/weighted_frontier_programs.jsonl")
    for c in search.candidates:
        if c.program.program_id==search.selected.program.program_id:continue
        mistakes.record(reason="equivalent_nonselected_weighted_program" if c.exact else "fails_weighted_outcome_world",candidate=c.program.to_dict(),evidence={"world_id":f["world_id"],"passed_examples":c.passed_example_count,"example_count":c.example_count,"exact":c.exact,"reward":c.reward,"does_not_enter_foundation_room":True})
    exact=[x for x in search.candidates if x.exact];ob=sum(x["passed"] for x in proof["obligations"]);hid=sum(x["passed"] for x in proof["case_results"])
    gates=[{"gate_id":"weighted_gap_taken_from_frontier","passed":f["missing_dependency"]=="weighted_sum_accumulator","actual":f,"required":"recorded gap"},{"gate_id":"anonymous_weighted_programs_compete","passed":search.candidates_evaluated==32,"actual":search.candidates_evaluated,"required":32},{"gate_id":"value_weight_over_total_weight_selected","passed":search.selected.program.term_mode==2 and search.selected.program.denominator_mode==2 and search.selected.program.normalize,"actual":search.selected.program.to_dict(),"required":"anonymous exact mode"},{"gate_id":"weighted_world_exactly_compressed","passed":search.selected.exact,"actual":search.selected.passed_example_count,"required":search.selected.example_count},{"gate_id":"weighted_semantic_universally_proved","passed":proof["passed"],"actual":ob,"required":len(proof["obligations"])},{"gate_id":"all_hidden_weighted_cases_pass","passed":hid==len(proof["case_results"]),"actual":hid,"required":len(proof["case_results"])},{"gate_id":"binomial_expectation_cases_pass","passed":all(x["passed"] for x in proof["binomial_expectation_cases"]),"actual":len(proof["binomial_expectation_cases"]),"required":len(proof["binomial_expectation_cases"])},{"gate_id":"accumulation_tokens_not_hidden","passed":all(x["primitive_execution_tokens"]>=x["accumulation_tokens"] for x in proof["case_results"]),"actual":True,"required":True},{"gate_id":"success_and_mistake_feedback_persist","passed":len(room.records)==1 and len(mistakes.records)>=31,"actual":{"success":len(room.records),"mistakes":len(mistakes.records)},"required":{"success":1,"mistakes":31}},{"gate_id":"user_did_not_specify_mean_or_expectation","passed":True,"actual":False,"required":False}]
    if not all(x["passed"] for x in gates):print(json.dumps({"verdict":"failed","gates":gates},ensure_ascii=False,indent=2));return 1
    now=datetime.now(timezone.utc);run_id="RUN-autonomous-weighted-"+now.strftime("%Y%m%dT%H%M%S%fZ");rd=ROOT/"artifacts/runs"/run_id;rd.mkdir(parents=True)
    report={"report_version":"autonomous-weighted-accumulation-v0.1","run_id":run_id,"created_at":now.isoformat().replace("+00:00","Z"),"verdict":"weighted_sum_accumulator_invented_and_finite_expectation_derived","resumed_from":{"run_id":prior["run_id"],"frontier":f,"user_supplied_math_target":False},"search":{"candidate_count":search.candidates_evaluated,"exact_candidate_count":len(exact),"selected_program":search.selected.program.to_dict(),"selected_token_cost":search.selected.total_token_cost,"selected_reward":search.selected.reward},"discovery":{"foundation_level":12,"semantic":semantic.to_dict(),"structural_origin":proof["structural_statement"],"posthoc_name":proof["posthoc_mathematical_name"],"posthoc_formula":proof["posthoc_formula"],"name_given_to_search":False,"counts_as_new_foundation":True},"derived_results":proof["derived_results"],"verification":proof,"capability_graph":{"verified_foundation_count":12,"new_foundation":"加权和累积器","verified_derived_results_added":2},"next_frontier":{"world_id":"WORLD-dispersion-around-center-84","structural_signature":"finite_weighted_dispersion","status":"dependency_blocked","missing_dependency":"signed_rational_arithmetic","posthoc_math_name":None},"rooms":{"success":"artifacts/foundation/success/weighted_frontier_semantics.jsonl","mistakes":"artifacts/foundation/mistakes/weighted_frontier_programs.jsonl","success_count":len(room.records),"mistake_count":len(mistakes.records),"event_hash":event["event_hash"]},"gates":gates,"limitations":["Only nonnegative integer outcomes and positive natural weights are proved.","Signed rational arithmetic, variance, covariance, and infinite expectations remain undiscovered.","Unary repeated accumulation is inefficient for large values."]}
    artifact=rd/"autonomous_weighted_report.json";artifact.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    for d in (ROOT/"reports/data/autonomous_weighted_latest.json",ROOT/"dashboard/data/autonomous_weighted_latest.json",ROOT/"artifacts/foundation/autonomous_weighted_latest.json"):d.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(artifact,d)
    print(json.dumps({"run_id":run_id,"semantic_id":semantic.semantic_id,"posthoc_name":proof["posthoc_mathematical_name"],"derived_results":proof["derived_results"],"search":f"{len(exact)}/{search.candidates_evaluated}","proof":f"{ob}/{len(proof['obligations'])}","hidden":f"{hid}/{len(proof['case_results'])}","foundation_count":12,"next_blocked_dependency":report["next_frontier"]["missing_dependency"],"artifact_path":artifact.relative_to(ROOT).as_posix()},ensure_ascii=True,indent=2));return 0
if __name__=="__main__":raise SystemExit(main())
