import data from "../../data/nasa_v41_blind_challenge_latest.json";

const r=data,q=r.challenge,p=q.performance_audit,s=p.by_life_stage,c=p.by_cell,g=q.challenge_gates,f=q.counterexample;
const stageRows=[["早期",s.early.rmse,p.early_stage_passed],["中期",s.middle.rmse,p.middle_stage_passed],["后期",s.late.rmse,p.late_stage_passed]] as const;
const modelRows=[["STATE_FOLD",p.overall.rmse],["STATELESS",p.candidate_comparison.stateless.rmse],["PERSISTENCE",p.candidate_comparison.persistence.rmse]] as const;
const maxModel=Math.max(...modelRows.map(item=>item[1]));
const gates=[
  ["承诺后挑战完整性",g.post_commit_challenge_integrity],["两个未见电池",g.two_unseen_cells],
  ["三个寿命阶段",g.three_life_stages],["参数没有重拟合",g.no_parameter_refit],
  ["STATE_FOLD 总体最优",g.state_fold_still_best_overall],["初始状态具有作用",g.initial_state_is_causally_useful],
  ["早期泛化",g.early_stage_generalization],["中期泛化",g.middle_stage_generalization],
  ["后期泛化",g.late_stage_generalization],["总体中位百分比误差",g.overall_median_percentage_error],
];

export default function Page(){return <main>
<header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">NASA BLIND CHALLENGE V41</p><p className="brand-name">AKGM-N0 / 冻结模型跨寿命压力测试</p></div></div><div className="run-meta"><a className="nav-link" href="/science-v41">动态发现 V41</a><a className="nav-link" href="/science-v40">物理装置 V40</a><a className="nav-link" href="/">总览</a></div></header>
<section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">挑战完成 · 适用域受限</span><span className="scope-label">FREEZE → REVEAL RW5/RW6 → STRESS → COUNTEREXAMPLE → RESTRICT</span></div><h1>STATE_FOLD 通过早中期迁移，但在晚期退化中失效</h1><p className="lede">模型参数在挑战数据生成前已经封存，没有重训练。120 条此前未见的 RW5、RW6 轨迹覆盖三个寿命阶段；后期 RMSE 超过预注册上限，因此系统撤销“全寿命通用”声明并登记反例。</p><div className="run-id"><span>LATEST</span><code>{r.run_id}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring"><strong>BOUND</strong><span>适用域已收缩</span></div><p>这是有效失败，不是验收事故</p></div></section>
<section className="metric-grid"><article className="metric-card accent-cyan"><p>盲测轨迹</p><strong>{q.provenance_audit.trace_count}</strong><span>RW5 60 / RW6 60</span></article><article className="metric-card accent-violet"><p>总体 RMSE</p><strong>{p.overall.rmse.toFixed(3)}</strong><span>中位误差 {(p.overall.median_absolute_percentage_error*100).toFixed(2)}%</span></article><article className="metric-card accent-amber"><p>晚期 RMSE</p><strong>{s.late.rmse.toFixed(3)}</strong><span>上限 {f.expected_max_rmse.toFixed(2)}</span></article><article className="metric-card accent-cyan"><p>破坏初态后</p><strong>{p.state_corruption_rmse_ratio.toFixed(2)}×</strong><span>证明记忆仍然有用</span></article></section>
<section className="content-grid operation-grid"><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">LIFE-STAGE TRANSFER</p><h2>误差随寿命阶段上升</h2></div></div><div className="bar-chart">{stageRows.map(([name,value,passed])=><div className="bar-row" key={name}><div className="bar-label"><span>{name}</span><strong>{value.toFixed(5)} · {passed?"PASS":"FAIL"}</strong></div><div className="bar-track"><div className={`bar ${passed?"library":"baseline"}`} style={{width:`${Math.min(100,value/0.18*100)}%`}} /></div></div>)}</div></article><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">MODEL COMPETITION</p><h2>状态模型仍是总体最优</h2></div></div><div className="bar-chart">{modelRows.map(([name,value])=><div className="bar-row" key={name}><div className="bar-label"><span>{name}</span><strong>{value.toFixed(5)}</strong></div><div className="bar-track"><div className={`bar ${name==="STATE_FOLD"?"library":"baseline"}`} style={{width:`${100*value/maxModel}%`}} /></div></div>)}</div><p className="concept-footnote">胜过替代模型并不代表跨所有阶段合格；两项判断必须分开。</p></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">COUNTEREXAMPLE ROOM</p><h2>晚期退化失效已进入错题库</h2></div></div><div className="posthoc-note"><strong>{f.failure_id}</strong><small>观测 RMSE {f.observed_rmse.toFixed(5)} ＞ 上限 {f.expected_max_rmse.toFixed(2)}。处理：{f.action}。</small></div><div className="boundary-box"><p>撤销的声明</p><code>UNIVERSAL_ALL_LIFE_STATE_FOLD</code><span>保留范围：NASA RW 系列早期与中期轨迹；晚期需要创造额外的老化状态。</span></div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">CHALLENGE GATES</p><h2>协议通过，晚期能力失败</h2></div></div><div className="operator-discovery-grid">{gates.map(([name,passed])=><article className="metric-card" key={String(name)}><p>{name}</p><strong className="operator-name">{passed?"PASS":"FAIL"}</strong><span>{passed?"证据已登记":"反例已登记"}</span></article>)}<article className="metric-card"><p>全寿命通用模型</p><strong className="operator-name">BLOCKED</strong><span>禁止继续使用该声明</span></article></div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">NEXT KNOWLEDGE GAP</p><h2>下一次创造目标：慢变量老化状态</h2></div></div><div className="boundary-box"><p>当前标签</p><code>{q.claim_state.current_label}</code><span>下一阶段应在快速脉冲状态之外，创造一个跨循环缓慢变化的记忆层，并重新接受同一组冻结盲测。</span></div></section>
</main>}
