import data from "../../data/scientific_discovery_v36_latest.json";
const r=data,a=r.acceptance,f=a.frontier_world,d=f.discovery,c=a.claim_state,g=a.discovery_gates;
const gateRows=[
  ["盲数据接口",g.blind_data_interface],["主动区分模型",g.active_model_discrimination],
  ["唯一可执行假设",g.unique_executable_hypothesis],["未来预测预注册",g.prospective_prediction],
  ["承诺早于揭晓",g.commit_before_reveal],["独立合成复现",g.independent_replication],
  ["反例审计",g.counterexample_audit],["本地目录未匹配",g.local_catalog_unmatched],
  ["全球文献新颖性",g.global_literature_novelty],["真实世界观测",g.real_world_observation],
  ["外部实验室复现",g.external_lab_replication],
];
export default function Page(){return <main><header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">SCIENTIFIC DISCOVERY MACHINE V36</p><p className="brand-name">AKGM-N0 / 从公式搜索到科学声明门控</p></div></div><div className="run-meta"><a className="nav-link" href="/science-v37">真实数据 V37</a><a className="nav-link" href="/mechanics-v35">力学 15/15</a><a className="nav-link" href="/meta-autonomy">自主循环</a><a className="nav-link" href="/">总览</a></div></header>
<section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">V36 验收 12/12</span><span className="scope-label">BLIND → DISAGREE → COMMIT → REVEAL → REPLICATE → TRIAGE</span></div><h1>科学发现流程已建立；“人类未知”声明仍被门控</h1><p className="lede">系统从 5,385 个匿名竞争程序出发，主动挑选两项判别实验，提交密封未来预测，再接受独立复现和反例攻击。结果只进入局部新候选室，不进入人类新发现室。</p><div className="run-id"><span>LATEST</span><code>{r.run_id}</code><code>{a.classification}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>{c.workflow_capability_verified?"READY":"BLOCK"}</strong><span>发现流程</span></div><p>人类未知声明：{c.human_unknown_claim_allowed?"允许":"禁止"}</p></div></section>
<section className="metric-grid meta-score-grid"><article className="metric-card accent-cyan"><p>竞争模型</p><strong>{d.initial_candidate_count.toLocaleString()}</strong><span>统一盲语法</span></article><article className="metric-card accent-violet"><p>主动实验</p><strong>{d.active_experiments.length}</strong><span>最终候选 {d.final_candidate_count}</span></article><article className="metric-card accent-amber"><p>密封预测</p><strong>{f.preregistration.passed?"PASS":"FAIL"}</strong><span>承诺先于揭晓</span></article><article className="metric-card accent-cyan"><p>独立复现</p><strong>{a.independent_replication.passed?"PASS":"FAIL"}</strong><span>{a.independent_replication.cases.length} 个域外点</span></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">LOCAL NOVEL CANDIDATE</p><h2>机器内部候选</h2></div></div><div className="operator-discovery-grid"><article className="metric-card"><p>OPAQUE PROGRAM</p><strong className="operator-name" style={{minWidth:0}}><code style={{fontSize:"0.82rem",overflowWrap:"anywhere",whiteSpace:"normal"}}>{d.selected_program.opaque_program}</code></strong><span>搜索时无公式名称</span></article><article className="metric-card"><p>POSTHOC</p><strong className="operator-name">2+q₀−q₁+q₀q₁</strong><span>合成黑盒规律</span></article><article className="metric-card"><p>CLAIM LABEL</p><strong className="operator-name" style={{fontSize:"0.82rem",overflowWrap:"anywhere"}}>{c.current_label}</strong><span>不是人类未知发现</span></article></div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">DISCOVERY GATES</p><h2>通过与未通过必须同时显示</h2></div></div><div className="operator-discovery-grid">{gateRows.map(([name,passed])=><article className="metric-card" key={String(name)}><p>{name}</p><strong className="operator-name">{passed?"PASS":"BLOCKED"}</strong><span>{passed?"已有机器证据":"不得升级声明"}</span></article>)}</div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">HONEST BOUNDARY</p><h2>这次推进完成了什么</h2></div></div><div className="boundary-box"><p>当前结论</p><code>{c.current_label}</code><span>真实数据、全球文献查重和外部实验室复现仍是硬缺口。</span></div><ul>{a.limitations.map(i=><li key={i}>{i}</li>)}</ul></section></main>}
