import reportData from "../../data/linear_algebra_foundation_v9_latest.json";
const report=reportData;const foundation=report.foundation;
const labels=["索引收缩","二次不变量","逆变换","特征约简"];
export default function FoundationV9Page(){return <main>
  <header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">LINEAR ALGEBRA BENCHMARK V9</p><p className="brand-name">AKGM-N0 / 有界匿名再发现</p></div></div><div className="run-meta"><a className="nav-link" href="/foundation-v10">严格新基础</a><a className="nav-link" href="/foundation-v8">V8能力测试</a><a className="nav-link" href="/meta-autonomy">自主探索</a><a className="nav-link" href="/foundation">基础记录</a><a className="nav-link" href="/">总览</a></div></header>
  <section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">4个线性代数能力测试通过</span><span className="scope-label">BOUNDED ANONYMOUS REDISCOVERY</span></div><h1>V9验证了执行与证明能力，不计作严格自主新基础</h1><p className="lede">这些实验包含主机提供的索引收缩、行列式分母和特征约简结构，因此保留为可复现能力测试，不再声称是完全自主创造。</p><div className="run-id"><span>LATEST</span><code>{report.run_id}</code><code>{report.verdict}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>4</strong><span>能力测试</span></div><p>精确2×2有理域</p></div></section>
  <section className="metric-grid meta-score-grid">{foundation.foundation.candidate_counts.map((count,index)=><article className="metric-card accent-cyan" key={labels[index]}><p>{labels[index]}</p><strong>{count}</strong><span>精确候选 {foundation.foundation.exact_counts[index]}</span></article>)}</section>
  <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">FOUNDATIONS 21–24</p><h2>独立符号证明</h2></div><span className="status-chip good">ALL PASS</span></div><div className="operator-discovery-grid">{foundation.proof.foundations.map(item=><article className="metric-card" key={item.semantic_id}><p><code>LEVEL {item.foundation_level} · {item.semantic_id}</code></p><strong className="operator-name">{item.posthoc_name}</strong><span>{item.universal_statement}</span><small>{item.obligations.filter(value=>value.passed).length}/{item.obligations.length} obligations</small></article>)}</div></section>
  <section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">HONEST BOUNDARY</p><h2>当前限定为2×2有理线性代数</h2></div></div><ul>{foundation.limitations.map(item=><li key={item}>{item}</li>)}</ul><p className="digest-line">内容摘要 <code>{foundation.content_digest}</code></p></section>
</main>}
