import data from "../../data/external_physical_science_v40_latest.json";

const r=data,a=r.acceptance,p=a.adaptive_experiment_audit,h=a.prospective_holdout_audit,x=a.new_process_replication_audit,q=a.physical_receipt_audit,s=a.created_semantic,g=a.discovery_gates,c=a.claim_state;
const observations=[...a.observations].sort((left,right)=>left.anonymous_control-right.anonymous_control);
const minResponse=Math.min(...observations.map(item=>item.anonymous_response));
const maxResponse=Math.max(...observations.map(item=>item.anonymous_response));
const passedGates=[
  ["外部物理装置",g.external_physical_apparatus],["现场传感测量",g.fresh_sensor_measurements],
  ["装置进程隔离",g.isolated_apparatus_process],["学习器领域盲化",g.domain_blind_learner],
  ["控制范围安全",g.bounded_safe_controls],["自适应选择实验",g.adaptive_experiment_selection],
  ["干预顺序随机化",g.randomized_intervention_order],["先承诺后测量",g.commit_before_measurement],
  ["未见条件预测",g.prospective_holdout_prediction],["新进程复现",g.new_process_replication],
  ["物理响应可区分",g.physical_response_varies],["原始回执唯一",g.raw_receipts_unique],
  ["原图隐私删除",g.privacy_preserving_raw_deletion],["新局部语义生成",g.new_local_semantic_created],
];

export default function Page(){return <main>
<header className="masthead"><div className="brand-lockup"><span className="brand-mark gen1-mark">●</span><div><p className="eyebrow">EXTERNAL PHYSICAL SCIENCE V40</p><p className="brand-name">AKGM-N0 / 匿名外部光学装置实验</p></div></div><div className="run-meta"><a className="nav-link" href="/science-v41">NASA 动态 V41</a><a className="nav-link" href="/science-v39">在线实验 V39</a><a className="nav-link" href="/science-v38">受控实验 V38</a><a className="nav-link" href="/">总览</a></div></header>
<section className="hero panel-grid operation-hero"><div className="hero-copy"><div className="verdict-row"><span className="verdict-badge">V40 验收 16/16</span><span className="scope-label">BLIND → COMMIT → ACTUATE → SENSE → ADAPT → REPLICATE</span></div><h1>系统第一次连接并研究了真正的外部物理装置</h1><p className="lede">学习器只看到八个匿名控制档位与匿名响应。独立代理在承诺后驱动实体光学扫描仪，每次生成现场传感数据、设备时间戳和唯一哈希；原始图像在统计后立即删除。</p><div className="run-id"><span>LATEST</span><code>{r.run_id}</code></div></div><div className="hero-signal compact-signal"><div className="signal-ring full-ring"><strong>{a.passed?"PASS":"BLOCK"}</strong><span>外部物理闭环</span></div><p>未知自然定律：仍阻断</p></div></section>
<section className="metric-grid"><article className="metric-card accent-cyan"><p>物理设备收据</p><strong>{q.receipt_count}</strong><span>{q.unique_raw_digest_count} 个唯一原始哈希</span></article><article className="metric-card accent-violet"><p>自适应轮次</p><strong>{p.round_count}</strong><span>{p.training_level_count} 个训练干预</span></article><article className="metric-card accent-amber"><p>未见档位误差</p><strong>{(h.absolute_percentage_error*100).toFixed(2)}%</strong><span>预测先于硬件扫描</span></article><article className="metric-card accent-cyan"><p>新进程复现误差</p><strong>{(x.median_absolute_percentage_error*100).toFixed(2)}%</strong><span>两个保留档位</span></article></section>
<section className="content-grid operation-grid"><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">ANONYMOUS RESPONSE MAP</p><h2>八个现场物理响应</h2></div><span className="evidence-chip">跨度 {q.response_range.toFixed(3)}</span></div><div className="bar-chart">{observations.map(item=>{const width=20+70*(item.anonymous_response-minResponse)/Math.max(maxResponse-minResponse,1e-9);return <div className="bar-row" key={item.anonymous_control}><div className="bar-label"><span>Q0={item.anonymous_control}</span><strong>{item.anonymous_response.toFixed(5)}</strong></div><div className="bar-track"><div className="bar library" style={{width:`${width}%`}} /></div><small>digest {item.raw_digest.slice(0,16)}…</small></div>})}</div></article><article className="surface concept-card"><div className="section-heading"><div><p className="eyebrow">CREATED SEMANTIC</p><h2>局部记忆与邻域增量</h2></div></div><div className="boundary-box"><p>{s.semantic_id}</p><code>{s.opaque_program}</code><span>没有提供领域公式；由 {s.knot_count} 个现场观测结点构造。</span></div><div className="posthoc-note"><strong>Holdout Q0={h.anonymous_level}</strong><small>预测 {h.predicted.toFixed(6)}，实测 {h.observed.toFixed(6)}；承诺事件 {h.prediction_commit_event_index} 早于测量事件 {h.measurement_event_index}。</small></div></article></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">ADAPTIVE EXPERIMENTS</p><h2>知识缺口决定下一次装置操作</h2></div></div><div className="operator-discovery-grid">{p.plans.map(plan=><article className="metric-card" key={plan.round_index}><p>ROUND {plan.round_index}</p><strong className="operator-name">[{plan.selected_levels.join(", ")}]</strong><span>{plan.reason}<br/>gap score {plan.maximum_gap_score.toFixed(3)}</span></article>)}</div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">PHYSICAL VERIFICATION GATES</p><h2>硬件证据链完整</h2></div></div><div className="operator-discovery-grid">{passedGates.map(([name,passed])=><article className="metric-card" key={String(name)}><p>{name}</p><strong className="operator-name">{passed?"PASS":"FAIL"}</strong><span>{passed?"证据已登记":"禁止验收"}</span></article>)}<article className="metric-card"><p>人类未知自然定律</p><strong className="operator-name">BLOCKED</strong><span>证据不足，禁止升级声明</span></article></div></section>
<section className="evidence-panel limitations-panel"><div className="section-heading"><div><p className="eyebrow">CLAIM BOUNDARY</p><h2>外部物理实验成功，不等于发现新自然定律</h2></div></div><div className="boundary-box"><p>当前标签</p><code>{c.current_label}</code><span>事后解释：匿名控制是扫描仪安全亮度档位，匿名响应是 96×96 光学采样区的归一化平均亮度。</span></div><ul>{a.limitations.map(item=><li key={item}>{item}</li>)}</ul></section>
</main>}
